-- =============================================================
-- 구매시스템 DDL - 01. 공통/기반 (로그인·공통코드·권한·메뉴)
-- DBMS: Oracle 23 Free / Schema: PURCHASE
-- 표준: 대리키 ID(IDENTITY) + 업무UK / COMP_CD 다법인 / 논리삭제 DEL_YN
-- =============================================================

-- ---------- CM_COMPANY (회사/법인) ----------
CREATE TABLE CM_COMPANY (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD    VARCHAR2(18 CHAR) NOT NULL,
  COMP_NM    VARCHAR2(200 CHAR) NOT NULL,
  BIZ_NO     VARCHAR2(20 CHAR),
  CEO_NM     VARCHAR2(100 CHAR),
  ADDR       VARCHAR2(300 CHAR),
  TEL        VARCHAR2(50 CHAR),
  USE_YN     CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN     CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID     VARCHAR2(18 CHAR),
  MOD_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_CM_COMPANY_1 UNIQUE (COMP_CD)
);
COMMENT ON TABLE CM_COMPANY IS '회사/법인';
COMMENT ON COLUMN CM_COMPANY.COMP_CD IS '회사코드';
COMMENT ON COLUMN CM_COMPANY.COMP_NM IS '회사명';

-- ---------- CM_CODE_GRP (공통코드 그룹) ----------
CREATE TABLE CM_CODE_GRP (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD    VARCHAR2(18 CHAR) DEFAULT '*' NOT NULL,
  GRP_CD     VARCHAR2(50 CHAR) NOT NULL,
  GRP_NM     VARCHAR2(200 CHAR) NOT NULL,
  DESCRIPTION VARCHAR2(500 CHAR),
  USE_YN     CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN     CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID     VARCHAR2(18 CHAR),
  MOD_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_CM_CODE_GRP_1 UNIQUE (COMP_CD, GRP_CD)
);
COMMENT ON TABLE CM_CODE_GRP IS '공통코드 그룹';
COMMENT ON COLUMN CM_CODE_GRP.GRP_CD IS '코드그룹';
COMMENT ON COLUMN CM_CODE_GRP.GRP_NM IS '코드그룹명';

-- ---------- CM_CODE (공통코드 상세) ----------
CREATE TABLE CM_CODE (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD    VARCHAR2(18 CHAR) DEFAULT '*' NOT NULL,
  GRP_CD     VARCHAR2(50 CHAR) NOT NULL,
  CD         VARCHAR2(50 CHAR) NOT NULL,
  CD_NM_KO   VARCHAR2(200 CHAR) NOT NULL,
  CD_NM_EN   VARCHAR2(200 CHAR),
  SORT_NO    NUMBER DEFAULT 1,
  ATTR1      VARCHAR2(200 CHAR),
  ATTR2      VARCHAR2(200 CHAR),
  ATTR3      VARCHAR2(200 CHAR),
  ATTR4      VARCHAR2(200 CHAR),
  USE_YN     CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN     CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID     VARCHAR2(18 CHAR),
  MOD_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_CM_CODE_1 UNIQUE (COMP_CD, GRP_CD, CD)
);
COMMENT ON TABLE CM_CODE IS '공통코드 상세';
COMMENT ON COLUMN CM_CODE.GRP_CD IS '코드그룹';
COMMENT ON COLUMN CM_CODE.CD IS '코드';
COMMENT ON COLUMN CM_CODE.CD_NM_KO IS '코드명(국문)';
COMMENT ON COLUMN CM_CODE.CD_NM_EN IS '코드명(영문)';
COMMENT ON COLUMN CM_CODE.SORT_NO IS '정렬순서';

-- ---------- CM_USER (사용자) ----------
CREATE TABLE CM_USER (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD    VARCHAR2(18 CHAR) NOT NULL,
  USR_ID     VARCHAR2(18 CHAR) NOT NULL,
  USR_NM     VARCHAR2(100 CHAR) NOT NULL,
  LOGIN_ID   VARCHAR2(50 CHAR) NOT NULL,
  PWD_HASH   VARCHAR2(200 CHAR),
  DEPT_CD    VARCHAR2(18 CHAR),
  POS_CD     VARCHAR2(18 CHAR),
  EMAIL      VARCHAR2(100 CHAR),
  MOBILE     VARCHAR2(50 CHAR),
  PURC_GRP_CD VARCHAR2(18 CHAR),
  LANG_CD    VARCHAR2(10 CHAR) DEFAULT 'ko',
  USR_TYP    VARCHAR2(18 CHAR) DEFAULT 'EMP',  -- EMP 임직원 / VENDOR 협력사
  PWD_FAIL_CNT NUMBER DEFAULT 0,
  LAST_LOGIN_DT TIMESTAMP(0) WITH LOCAL TIME ZONE,
  USE_YN     CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN     CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID     VARCHAR2(18 CHAR),
  MOD_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_CM_USER_1 UNIQUE (COMP_CD, USR_ID),
  CONSTRAINT UX_CM_USER_2 UNIQUE (LOGIN_ID)
);
COMMENT ON TABLE CM_USER IS '사용자';
COMMENT ON COLUMN CM_USER.USR_ID IS '사용자ID(사번)';
COMMENT ON COLUMN CM_USER.LOGIN_ID IS '로그인ID';
COMMENT ON COLUMN CM_USER.PWD_HASH IS '비밀번호 해시(BCrypt)';
COMMENT ON COLUMN CM_USER.USR_TYP IS '사용자유형(EMP/VENDOR)';

-- ---------- CM_MENU (메뉴) ----------
CREATE TABLE CM_MENU (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  MENU_ID    VARCHAR2(30 CHAR) NOT NULL,
  MENU_NM    VARCHAR2(100 CHAR) NOT NULL,
  UP_MENU_ID VARCHAR2(30 CHAR),
  MENU_LVL   NUMBER DEFAULT 1,
  URL        VARCHAR2(200 CHAR),
  ICON       VARCHAR2(50 CHAR),
  SORT_NO    NUMBER DEFAULT 1,
  USE_YN     CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN     CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID     VARCHAR2(18 CHAR),
  MOD_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_CM_MENU_1 UNIQUE (MENU_ID)
);
COMMENT ON TABLE CM_MENU IS '메뉴';
COMMENT ON COLUMN CM_MENU.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN CM_MENU.UP_MENU_ID IS '상위메뉴ID';
COMMENT ON COLUMN CM_MENU.URL IS '화면 경로';

-- ---------- CM_ROLE (역할) ----------
CREATE TABLE CM_ROLE (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ROLE_ID    VARCHAR2(30 CHAR) NOT NULL,
  ROLE_NM    VARCHAR2(100 CHAR) NOT NULL,
  DESCRIPTION VARCHAR2(500 CHAR),
  USE_YN     CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN     CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID     VARCHAR2(18 CHAR),
  MOD_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_CM_ROLE_1 UNIQUE (ROLE_ID)
);
COMMENT ON TABLE CM_ROLE IS '역할';

-- ---------- CM_ROLE_FUNC (역할별 메뉴권한) ----------
CREATE TABLE CM_ROLE_FUNC (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ROLE_ID    VARCHAR2(30 CHAR) NOT NULL,
  MENU_ID    VARCHAR2(30 CHAR) NOT NULL,
  AUTH_CD    VARCHAR2(18 CHAR) DEFAULT 'READ' NOT NULL, -- READ/SAVE/APPROVAL/MANAGEMENT
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_CM_ROLE_FUNC_1 UNIQUE (ROLE_ID, MENU_ID)
);
COMMENT ON TABLE CM_ROLE_FUNC IS '역할별 메뉴권한';
COMMENT ON COLUMN CM_ROLE_FUNC.AUTH_CD IS '권한(READ/SAVE/APPROVAL/MANAGEMENT)';

-- ---------- CM_USER_ROLE (사용자별 역할) ----------
CREATE TABLE CM_USER_ROLE (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD    VARCHAR2(18 CHAR) NOT NULL,
  USR_ID     VARCHAR2(18 CHAR) NOT NULL,
  ROLE_ID    VARCHAR2(30 CHAR) NOT NULL,
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_CM_USER_ROLE_1 UNIQUE (COMP_CD, USR_ID, ROLE_ID)
);
COMMENT ON TABLE CM_USER_ROLE IS '사용자별 역할';
