-- =============================================================
-- 구매시스템 DDL - 03. 구매요청(PR) + 공통(채번/상태전이/상태이력)
-- =============================================================

-- ---------- CM_DOC_NO (문서번호 채번 규칙) ----------
CREATE TABLE CM_DOC_NO (
  ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DOC_TYP   VARCHAR2(18 CHAR) NOT NULL,
  DOC_NM    VARCHAR2(100 CHAR),
  PREFIX    VARCHAR2(10 CHAR),
  DATE_FMT  VARCHAR2(10 CHAR),          -- YYYYMM 등
  SEQ_LEN   NUMBER DEFAULT 4,
  LAST_YMD  VARCHAR2(8 CHAR),           -- 마지막 채번 기준일(리셋 단위)
  LAST_SEQ  NUMBER DEFAULT 0,
  USE_YN    CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN    CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID    VARCHAR2(18 CHAR),
  REG_DT    TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID    VARCHAR2(18 CHAR),
  MOD_DT    TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_CM_DOC_NO_1 UNIQUE (DOC_TYP)
);
COMMENT ON TABLE CM_DOC_NO IS '문서번호 채번 규칙';
COMMENT ON COLUMN CM_DOC_NO.DOC_TYP IS '문서유형';
COMMENT ON COLUMN CM_DOC_NO.PREFIX IS '접두어';
COMMENT ON COLUMN CM_DOC_NO.DATE_FMT IS '일자포맷(채번 리셋단위)';
COMMENT ON COLUMN CM_DOC_NO.LAST_SEQ IS '마지막 채번 일련번호';

-- ---------- CM_STATUS_FLOW (상태전이 규칙) ----------
CREATE TABLE CM_STATUS_FLOW (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DOC_TYP    VARCHAR2(18 CHAR) NOT NULL,
  FROM_STS   VARCHAR2(18 CHAR) NOT NULL,
  ACTION     VARCHAR2(18 CHAR) NOT NULL,   -- SUBMIT/APPROVE/REJECT/RECALL/CANCEL/...
  TO_STS     VARCHAR2(18 CHAR) NOT NULL,
  ACTION_NM  VARCHAR2(50 CHAR) NOT NULL,   -- 버튼 라벨
  DIRECTION  VARCHAR2(10 CHAR) DEFAULT 'FWD', -- FWD 전진 / BWD 되돌리기 / END 종료
  RSN_REQ_YN CHAR(1 CHAR) DEFAULT 'N',      -- 사유 필수
  ALLOW_ROLE VARCHAR2(100 CHAR),            -- 허용 역할(콤마구분, NULL=전체)
  SORT_NO    NUMBER DEFAULT 1,
  USE_YN     CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN     CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID     VARCHAR2(18 CHAR),
  MOD_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_CM_STATUS_FLOW_1 UNIQUE (DOC_TYP, FROM_STS, ACTION)
);
COMMENT ON TABLE CM_STATUS_FLOW IS '문서 상태전이 규칙';
COMMENT ON COLUMN CM_STATUS_FLOW.ACTION IS '액션(SUBMIT/APPROVE/REJECT/RECALL/CANCEL)';
COMMENT ON COLUMN CM_STATUS_FLOW.DIRECTION IS '방향(FWD전진/BWD되돌리기/END종료)';

-- ---------- LOG_DOC_STATUS_HIS (문서 상태이력) ----------
CREATE TABLE LOG_DOC_STATUS_HIS (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DOC_TYP    VARCHAR2(18 CHAR) NOT NULL,
  DOC_ID     NUMBER NOT NULL,
  DOC_NO     VARCHAR2(30 CHAR),
  SEQ        NUMBER,
  FROM_STS   VARCHAR2(18 CHAR),
  TO_STS     VARCHAR2(18 CHAR),
  ACTION     VARCHAR2(18 CHAR),
  ACTION_NM  VARCHAR2(50 CHAR),
  ACTOR_ID   VARCHAR2(18 CHAR),
  ACTION_DT  TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  RSN        VARCHAR2(1000 CHAR)
);
COMMENT ON TABLE LOG_DOC_STATUS_HIS IS '문서 상태이력(전진/되돌리기)';
CREATE INDEX IX_LOG_DOC_STATUS_HIS_1 ON LOG_DOC_STATUS_HIS (DOC_TYP, DOC_ID, SEQ);

-- ---------- PR_REQUEST (구매요청 헤더) ----------
CREATE TABLE PR_REQUEST (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD     VARCHAR2(18 CHAR) NOT NULL,
  PR_NO       VARCHAR2(30 CHAR) NOT NULL,
  PR_TITLE    VARCHAR2(300 CHAR) NOT NULL,
  PR_TYP      VARCHAR2(18 CHAR) DEFAULT 'PRODUCT',
  PURC_GRP_CD VARCHAR2(18 CHAR),
  REQ_DEPT_CD VARCHAR2(18 CHAR),
  REQ_USR_ID  VARCHAR2(18 CHAR),
  OPER_ORG_CD VARCHAR2(18 CHAR),
  REQ_YMD     DATE,
  HOPE_DLV_YMD DATE,
  CURR_CD     VARCHAR2(3 CHAR) DEFAULT 'KRW',
  TOT_AMT     NUMBER(20,5) DEFAULT 0,
  STS         VARCHAR2(18 CHAR) DEFAULT 'TMP' NOT NULL,
  REMARK      VARCHAR2(2000 CHAR),
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_PR_REQUEST_1 UNIQUE (COMP_CD, PR_NO)
);
COMMENT ON TABLE PR_REQUEST IS '구매요청 헤더';
COMMENT ON COLUMN PR_REQUEST.PR_NO IS '구매요청번호';
COMMENT ON COLUMN PR_REQUEST.PR_TYP IS '요청유형(PRODUCT/SERVICE)';
COMMENT ON COLUMN PR_REQUEST.STS IS '진행상태(TMP/REQ/APRV/CANCEL)';

-- ---------- PR_ITEM (구매요청 품목) ----------
CREATE TABLE PR_ITEM (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  REQUEST_ID  NUMBER NOT NULL,
  LINE_NO     NUMBER NOT NULL,
  ITEM_CD     VARCHAR2(18 CHAR),
  NEW_ITEM_YN CHAR(1 CHAR) DEFAULT 'N',
  ITEM_NM     VARCHAR2(300 CHAR),
  SPEC        VARCHAR2(500 CHAR),
  UNIT_CD     VARCHAR2(18 CHAR),
  QTY         NUMBER(20,5) DEFAULT 0,
  EST_PRC     NUMBER(20,5) DEFAULT 0,
  AMT         NUMBER(20,5) DEFAULT 0,
  HOPE_DLV_YMD DATE,
  DLV_PLACE   VARCHAR2(300 CHAR),
  REMARK      VARCHAR2(1000 CHAR),
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_PR_ITEM_1 UNIQUE (REQUEST_ID, LINE_NO),
  CONSTRAINT FK_PR_ITEM_1 FOREIGN KEY (REQUEST_ID) REFERENCES PR_REQUEST (ID)
);
COMMENT ON TABLE PR_ITEM IS '구매요청 품목';
COMMENT ON COLUMN PR_ITEM.REQUEST_ID IS '구매요청 ID';
COMMENT ON COLUMN PR_ITEM.LINE_NO IS '품목 순번';
