-- =============================================================
-- 구매시스템 SEED - 04. 구매요청(PR) 관련
-- =============================================================

-- ---------- 구매요청 진행상태 코드 ----------
INSERT INTO CM_CODE_GRP (GRP_CD, GRP_NM, DESCRIPTION, REG_ID) VALUES ('PR_STS', '구매요청상태', 'PR 진행상태', 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('PR_STS', 'TMP', '작성중', 'Draft', 1, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('PR_STS', 'REQ', '상신(결재요청)', 'Submitted', 2, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('PR_STS', 'APRV', '결재완료', 'Approved', 3, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('PR_STS', 'CANCEL', '취소', 'Canceled', 9, 'SYSTEM');

-- ---------- 채번 규칙 (PR-YYYYMM-####) ----------
INSERT INTO CM_DOC_NO (DOC_TYP, DOC_NM, PREFIX, DATE_FMT, SEQ_LEN, LAST_SEQ, REG_ID)
VALUES ('PR', '구매요청', 'PR', 'YYYYMM', 4, 0, 'SYSTEM');

-- ---------- PR 상태전이 규칙 ----------
-- 전진
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('PR', 'TMP', 'SUBMIT', 'REQ', '상신', 'FWD', 'N', 1, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('PR', 'REQ', 'APPROVE', 'APRV', '결재완료', 'FWD', 'N', 1, 'SYSTEM');
-- 되돌리기
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('PR', 'REQ', 'REJECT', 'TMP', '반려', 'BWD', 'Y', 2, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('PR', 'REQ', 'RECALL', 'TMP', '회수', 'BWD', 'N', 3, 'SYSTEM');
-- 취소
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('PR', 'TMP', 'CANCEL', 'CANCEL', '취소', 'END', 'Y', 9, 'SYSTEM');

-- ---------- 메뉴: 구매(PRO) 그룹 + 구매요청 ----------
INSERT INTO CM_MENU (MENU_ID, MENU_NM, UP_MENU_ID, MENU_LVL, URL, ICON, SORT_NO, REG_ID) VALUES ('PRO', '구매', NULL, 1, NULL, 'cart', 10, 'SYSTEM');
INSERT INTO CM_MENU (MENU_ID, MENU_NM, UP_MENU_ID, MENU_LVL, URL, ICON, SORT_NO, REG_ID) VALUES ('PRO_PR', '구매요청', 'PRO', 2, '/pro/pr', 'file', 1, 'SYSTEM');

-- ---------- 권한: ADMIN(관리), USER(저장) ----------
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('ADMIN', 'PRO_PR', 'MANAGEMENT', 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('USER', 'PRO_PR', 'SAVE', 'SYSTEM');

COMMIT;
