-- =============================================================
-- 구매시스템 DDL - 05. 발주(PO)
-- =============================================================

-- ---------- PO_ORDER (발주 헤더) ----------
CREATE TABLE PO_ORDER (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD     VARCHAR2(18 CHAR) NOT NULL,
  PO_NO       VARCHAR2(30 CHAR) NOT NULL,
  PO_REV      NUMBER DEFAULT 0,
  PO_TITLE    VARCHAR2(300 CHAR) NOT NULL,
  VD_CD       VARCHAR2(18 CHAR),
  VD_NM       VARCHAR2(200 CHAR),
  PURC_GRP_CD VARCHAR2(18 CHAR),
  CHRG_USR_ID VARCHAR2(18 CHAR),
  OPER_ORG_CD VARCHAR2(18 CHAR),
  SRC_TYP     VARCHAR2(18 CHAR),          -- PR/RFX/AUCTION/CONTRACT/DIRECT
  SRC_ID      NUMBER,
  PO_YMD      DATE,
  DLV_YMD     DATE,
  DLV_COND    VARCHAR2(100 CHAR),
  PAY_COND    VARCHAR2(100 CHAR),
  CURR_CD     VARCHAR2(3 CHAR) DEFAULT 'KRW',
  SUPL_AMT    NUMBER(20,5) DEFAULT 0,
  VAT_AMT     NUMBER(20,5) DEFAULT 0,
  TOT_AMT     NUMBER(20,5) DEFAULT 0,
  STS         VARCHAR2(18 CHAR) DEFAULT 'TMP' NOT NULL,
  IF_STATUS   CHAR(1 CHAR) DEFAULT 'N',
  REMARK      VARCHAR2(2000 CHAR),
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_PO_ORDER_1 UNIQUE (COMP_CD, PO_NO)
);
COMMENT ON TABLE PO_ORDER IS '발주 헤더';
COMMENT ON COLUMN PO_ORDER.PO_NO IS '발주번호';
COMMENT ON COLUMN PO_ORDER.PO_REV IS '발주 수정판수';
COMMENT ON COLUMN PO_ORDER.VD_CD IS '협력사코드';
COMMENT ON COLUMN PO_ORDER.SRC_TYP IS '생성원천(PR/RFX/AUCTION/CONTRACT/DIRECT)';
COMMENT ON COLUMN PO_ORDER.STS IS '진행상태(TMP/REQ/PC/CANCEL)';

-- ---------- PO_ORDER_ITEM (발주 품목) ----------
CREATE TABLE PO_ORDER_ITEM (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ORDER_ID    NUMBER NOT NULL,
  LINE_NO     NUMBER NOT NULL,
  PR_ITEM_ID  NUMBER,
  ITEM_CD     VARCHAR2(18 CHAR),
  ITEM_NM     VARCHAR2(300 CHAR),
  SPEC        VARCHAR2(500 CHAR),
  UNIT_CD     VARCHAR2(18 CHAR),
  QTY         NUMBER(20,5) DEFAULT 0,
  PRC         NUMBER(20,5) DEFAULT 0,
  SUPL_AMT    NUMBER(20,5) DEFAULT 0,
  VAT_AMT     NUMBER(20,5) DEFAULT 0,
  AMT         NUMBER(20,5) DEFAULT 0,
  DLV_YMD     DATE,
  GR_QTY      NUMBER(20,5) DEFAULT 0,
  REMARK      VARCHAR2(1000 CHAR),
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_PO_ORDER_ITEM_1 UNIQUE (ORDER_ID, LINE_NO),
  CONSTRAINT FK_PO_ORDER_ITEM_1 FOREIGN KEY (ORDER_ID) REFERENCES PO_ORDER (ID)
);
COMMENT ON TABLE PO_ORDER_ITEM IS '발주 품목';
COMMENT ON COLUMN PO_ORDER_ITEM.GR_QTY IS '입고누계수량';
