-- =============================================================
-- 구매시스템 SEED - 06. 발주(PO) 관련
-- =============================================================

-- ---------- 발주 진행상태 코드 ----------
INSERT INTO CM_CODE_GRP (GRP_CD, GRP_NM, DESCRIPTION, REG_ID) VALUES ('PO_STS', '발주상태', 'PO 진행상태', 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('PO_STS', 'TMP', '작성중', 'Draft', 1, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('PO_STS', 'REQ', '상신(결재요청)', 'Submitted', 2, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('PO_STS', 'PC', '발주완료', 'Ordered', 3, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('PO_STS', 'CANCEL', '취소', 'Canceled', 9, 'SYSTEM');

-- ---------- 채번 규칙 (PO-YYYYMM-####) ----------
INSERT INTO CM_DOC_NO (DOC_TYP, DOC_NM, PREFIX, DATE_FMT, SEQ_LEN, LAST_SEQ, REG_ID)
VALUES ('PO', '발주', 'PO', 'YYYYMM', 4, 0, 'SYSTEM');

-- ---------- PO 상태전이 규칙 ----------
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('PO', 'TMP', 'SUBMIT', 'REQ', '상신', 'FWD', 'N', 1, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('PO', 'REQ', 'APPROVE', 'PC', '발주확정', 'FWD', 'N', 1, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('PO', 'REQ', 'REJECT', 'TMP', '반려', 'BWD', 'Y', 2, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('PO', 'REQ', 'RECALL', 'TMP', '회수', 'BWD', 'N', 3, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('PO', 'TMP', 'CANCEL', 'CANCEL', '취소', 'END', 'Y', 9, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('PO', 'PC', 'CANCEL', 'CANCEL', '발주취소', 'END', 'Y', 9, 'SYSTEM');

-- ---------- 메뉴 ----------
INSERT INTO CM_MENU (MENU_ID, MENU_NM, UP_MENU_ID, MENU_LVL, URL, ICON, SORT_NO, REG_ID) VALUES ('PRO_PO', '발주', 'PRO', 2, '/pro/po', 'file', 2, 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('ADMIN', 'PRO_PO', 'MANAGEMENT', 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('USER', 'PRO_PO', 'SAVE', 'SYSTEM');

COMMIT;
