-- =============================================================
-- 구매시스템 DDL - 07. 협력사(VD) + 품목분류/품목(IT)
-- =============================================================

-- ---------- VD_VENDOR (협력사) ----------
CREATE TABLE VD_VENDOR (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD     VARCHAR2(18 CHAR) NOT NULL,
  VD_CD       VARCHAR2(18 CHAR) NOT NULL,
  ERP_VD_CD   VARCHAR2(18 CHAR),
  VD_NM       VARCHAR2(200 CHAR) NOT NULL,
  VD_NM_EN    VARCHAR2(200 CHAR),
  BIZ_NO      VARCHAR2(20 CHAR),
  CORP_NO     VARCHAR2(20 CHAR),
  CEO_NM      VARCHAR2(100 CHAR),
  VD_TYP      VARCHAR2(18 CHAR),
  BIZ_COND    VARCHAR2(200 CHAR),
  BIZ_ITEM    VARCHAR2(200 CHAR),
  ADDR        VARCHAR2(300 CHAR),
  TEL         VARCHAR2(50 CHAR),
  FAX         VARCHAR2(50 CHAR),
  EMAIL       VARCHAR2(100 CHAR),
  PAY_COND    VARCHAR2(100 CHAR),
  VD_STS      VARCHAR2(18 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_VD_VENDOR_1 UNIQUE (COMP_CD, VD_CD)
);
COMMENT ON TABLE VD_VENDOR IS '협력사';
COMMENT ON COLUMN VD_VENDOR.VD_CD IS '협력사코드';
COMMENT ON COLUMN VD_VENDOR.VD_TYP IS '협력사유형(MFR/DST/SVC)';
COMMENT ON COLUMN VD_VENDOR.VD_STS IS '거래상태(ACTIVE/STOP)';

-- ---------- IT_CATEGORY (품목분류) ----------
CREATE TABLE IT_CATEGORY (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CATE_CD     VARCHAR2(18 CHAR) NOT NULL,
  CATE_NM     VARCHAR2(200 CHAR) NOT NULL,
  UP_CATE_CD  VARCHAR2(18 CHAR),
  CATE_LVL    NUMBER DEFAULT 1,
  SORT_NO     NUMBER DEFAULT 1,
  LEAF_YN     CHAR(1 CHAR) DEFAULT 'Y',
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_IT_CATEGORY_1 UNIQUE (CATE_CD)
);
COMMENT ON TABLE IT_CATEGORY IS '품목분류';
COMMENT ON COLUMN IT_CATEGORY.CATE_CD IS '분류코드';
COMMENT ON COLUMN IT_CATEGORY.UP_CATE_CD IS '상위분류코드';

-- ---------- IT_ITEM (품목마스터) ----------
CREATE TABLE IT_ITEM (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD     VARCHAR2(18 CHAR) NOT NULL,
  ITEM_CD     VARCHAR2(18 CHAR) NOT NULL,
  ERP_ITEM_CD VARCHAR2(18 CHAR),
  ITEM_NM     VARCHAR2(300 CHAR) NOT NULL,
  ITEM_NM_EN  VARCHAR2(300 CHAR),
  SPEC        VARCHAR2(500 CHAR),
  CATE_CD     VARCHAR2(18 CHAR),
  UNIT_CD     VARCHAR2(18 CHAR),
  ITEM_TYP    VARCHAR2(18 CHAR),
  TAX_TYP     VARCHAR2(18 CHAR) DEFAULT 'TAX',
  ITEM_STS    VARCHAR2(18 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  REMARK      VARCHAR2(1000 CHAR),
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_IT_ITEM_1 UNIQUE (COMP_CD, ITEM_CD)
);
COMMENT ON TABLE IT_ITEM IS '품목마스터';
COMMENT ON COLUMN IT_ITEM.ITEM_CD IS '품목코드';
COMMENT ON COLUMN IT_ITEM.CATE_CD IS '분류코드';
COMMENT ON COLUMN IT_ITEM.ITEM_TYP IS '품목유형(RAW/SUB/GOODS/SVC)';
COMMENT ON COLUMN IT_ITEM.ITEM_STS IS '품목상태(NEW/ACTIVE/STOP)';
