-- =============================================================
-- 구매시스템 DDL - 09. 입고/검수(GR)
-- =============================================================

-- ---------- GR_RECEIPT (입고/검수 헤더) ----------
CREATE TABLE GR_RECEIPT (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD     VARCHAR2(18 CHAR) NOT NULL,
  GR_NO       VARCHAR2(30 CHAR) NOT NULL,
  PO_ID       NUMBER NOT NULL,
  PO_NO       VARCHAR2(30 CHAR),
  VD_CD       VARCHAR2(18 CHAR),
  VD_NM       VARCHAR2(200 CHAR),
  OPER_ORG_CD VARCHAR2(18 CHAR),
  GR_YMD      DATE,
  INSP_USR_ID VARCHAR2(18 CHAR),
  INSP_YMD    DATE,
  TOT_AMT     NUMBER(20,5) DEFAULT 0,
  STS         VARCHAR2(18 CHAR) DEFAULT 'TMP' NOT NULL,
  IF_STATUS   CHAR(1 CHAR) DEFAULT 'N',
  REMARK      VARCHAR2(2000 CHAR),
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_GR_RECEIPT_1 UNIQUE (COMP_CD, GR_NO)
);
COMMENT ON TABLE GR_RECEIPT IS '입고/검수 헤더';
COMMENT ON COLUMN GR_RECEIPT.GR_NO IS '입고번호';
COMMENT ON COLUMN GR_RECEIPT.PO_ID IS '발주 ID';
COMMENT ON COLUMN GR_RECEIPT.STS IS '진행상태(TMP/CFM/CANCEL)';

-- ---------- GR_RECEIPT_ITEM (입고 품목) ----------
CREATE TABLE GR_RECEIPT_ITEM (
  ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RECEIPT_ID    NUMBER NOT NULL,
  LINE_NO       NUMBER NOT NULL,
  PO_ITEM_ID    NUMBER,
  ITEM_CD       VARCHAR2(18 CHAR),
  ITEM_NM       VARCHAR2(300 CHAR),
  SPEC          VARCHAR2(500 CHAR),
  UNIT_CD       VARCHAR2(18 CHAR),
  PO_QTY        NUMBER(20,5) DEFAULT 0,
  GR_QTY        NUMBER(20,5) DEFAULT 0,
  INSP_PASS_QTY NUMBER(20,5) DEFAULT 0,
  INSP_FAIL_QTY NUMBER(20,5) DEFAULT 0,
  PRC           NUMBER(20,5) DEFAULT 0,
  AMT           NUMBER(20,5) DEFAULT 0,
  INSP_RESULT   VARCHAR2(18 CHAR) DEFAULT 'PASS',
  REMARK        VARCHAR2(1000 CHAR),
  REG_ID        VARCHAR2(18 CHAR),
  REG_DT        TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID        VARCHAR2(18 CHAR),
  MOD_DT        TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_GR_RECEIPT_ITEM_1 UNIQUE (RECEIPT_ID, LINE_NO),
  CONSTRAINT FK_GR_RECEIPT_ITEM_1 FOREIGN KEY (RECEIPT_ID) REFERENCES GR_RECEIPT (ID)
);
COMMENT ON TABLE GR_RECEIPT_ITEM IS '입고 품목';
COMMENT ON COLUMN GR_RECEIPT_ITEM.PO_QTY IS '발주수량';
COMMENT ON COLUMN GR_RECEIPT_ITEM.GR_QTY IS '입고수량';
COMMENT ON COLUMN GR_RECEIPT_ITEM.INSP_RESULT IS '검사결과(PASS/FAIL/PARTIAL)';
