-- =============================================================
-- 구매시스템 SEED - 10. 입고/검수(GR) 관련
-- =============================================================

-- ---------- 입고 진행상태 코드 ----------
INSERT INTO CM_CODE_GRP (GRP_CD, GRP_NM, DESCRIPTION, REG_ID) VALUES ('GR_STS', '입고상태', 'GR 진행상태', 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('GR_STS', 'TMP', '작성중', 'Draft', 1, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('GR_STS', 'CFM', '입고확정', 'Confirmed', 2, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('GR_STS', 'CANCEL', '취소', 'Canceled', 9, 'SYSTEM');

-- ---------- 검사결과 코드 ----------
INSERT INTO CM_CODE_GRP (GRP_CD, GRP_NM, DESCRIPTION, REG_ID) VALUES ('INSP_RESULT', '검사결과', '', 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('INSP_RESULT', 'PASS', '합격', 'Pass', 1, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('INSP_RESULT', 'FAIL', '불합격', 'Fail', 2, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('INSP_RESULT', 'PARTIAL', '부분합격', 'Partial', 3, 'SYSTEM');

-- ---------- 채번 (GR-YYYYMM-####) ----------
INSERT INTO CM_DOC_NO (DOC_TYP, DOC_NM, PREFIX, DATE_FMT, SEQ_LEN, LAST_SEQ, REG_ID)
VALUES ('GR', '입고', 'GR', 'YYYYMM', 4, 0, 'SYSTEM');

-- ---------- GR 상태전이 ----------
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('GR', 'TMP', 'CONFIRM', 'CFM', '입고확정', 'FWD', 'N', 1, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('GR', 'TMP', 'CANCEL', 'CANCEL', '취소', 'END', 'Y', 9, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('GR', 'CFM', 'CANCEL', 'CANCEL', '입고취소', 'BWD', 'Y', 9, 'SYSTEM');

-- ---------- 메뉴 ----------
INSERT INTO CM_MENU (MENU_ID, MENU_NM, UP_MENU_ID, MENU_LVL, URL, ICON, SORT_NO, REG_ID) VALUES ('PRO_GR', '입고/검수', 'PRO', 2, '/pro/gr', 'inbox', 3, 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('ADMIN', 'PRO_GR', 'MANAGEMENT', 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('USER', 'PRO_GR', 'SAVE', 'SYSTEM');

COMMIT;
