-- =============================================================
-- 구매시스템 DDL - 11. 정산/마감(CL)
-- =============================================================

-- ---------- CL_CLOSE (정산마감 헤더) ----------
CREATE TABLE CL_CLOSE (
  ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD      VARCHAR2(18 CHAR) NOT NULL,
  CLOSE_NO     VARCHAR2(30 CHAR) NOT NULL,
  CLOSE_YM     VARCHAR2(6 CHAR) NOT NULL,
  VD_CD        VARCHAR2(18 CHAR),
  VD_NM        VARCHAR2(200 CHAR),
  TOT_SUPL_AMT NUMBER(20,5) DEFAULT 0,
  TOT_VAT_AMT  NUMBER(20,5) DEFAULT 0,
  TOT_AMT      NUMBER(20,5) DEFAULT 0,
  GR_CNT       NUMBER DEFAULT 0,
  LOCK_YN      CHAR(1 CHAR) DEFAULT 'N',
  STS          VARCHAR2(18 CHAR) DEFAULT 'TMP' NOT NULL,
  IF_STATUS    CHAR(1 CHAR) DEFAULT 'N',
  REMARK       VARCHAR2(2000 CHAR),
  USE_YN       CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN       CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID       VARCHAR2(18 CHAR),
  REG_DT       TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID       VARCHAR2(18 CHAR),
  MOD_DT       TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_CL_CLOSE_1 UNIQUE (COMP_CD, CLOSE_NO)
);
COMMENT ON TABLE CL_CLOSE IS '정산마감 헤더';
COMMENT ON COLUMN CL_CLOSE.CLOSE_YM IS '마감년월(YYYYMM)';
COMMENT ON COLUMN CL_CLOSE.LOCK_YN IS '마감잠금여부';
COMMENT ON COLUMN CL_CLOSE.STS IS '진행상태(TMP/CFM/CANCEL)';

-- ---------- CL_CLOSE_GR (마감대상 입고) ----------
CREATE TABLE CL_CLOSE_GR (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CLOSE_ID   NUMBER NOT NULL,
  GR_ID      NUMBER NOT NULL,
  GR_NO      VARCHAR2(30 CHAR),
  GR_YMD     DATE,
  PO_NO      VARCHAR2(30 CHAR),
  SUPL_AMT   NUMBER(20,5) DEFAULT 0,
  VAT_AMT    NUMBER(20,5) DEFAULT 0,
  AMT        NUMBER(20,5) DEFAULT 0,
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_CL_CLOSE_GR_1 UNIQUE (CLOSE_ID, GR_ID),
  CONSTRAINT FK_CL_CLOSE_GR_1 FOREIGN KEY (CLOSE_ID) REFERENCES CL_CLOSE (ID)
);
COMMENT ON TABLE CL_CLOSE_GR IS '마감대상 입고';
COMMENT ON COLUMN CL_CLOSE_GR.GR_ID IS '입고 ID';
