-- =============================================================
-- 구매시스템 SEED - 12. 정산/마감(CL) 관련
-- =============================================================

INSERT INTO CM_CODE_GRP (GRP_CD, GRP_NM, DESCRIPTION, REG_ID) VALUES ('CL_STS', '정산마감상태', '', 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('CL_STS', 'TMP', '작성중', 'Draft', 1, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('CL_STS', 'CFM', '마감확정', 'Confirmed', 2, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('CL_STS', 'CANCEL', '취소', 'Canceled', 9, 'SYSTEM');

INSERT INTO CM_DOC_NO (DOC_TYP, DOC_NM, PREFIX, DATE_FMT, SEQ_LEN, LAST_SEQ, REG_ID)
VALUES ('CL', '정산마감', 'CL', 'YYYYMM', 4, 0, 'SYSTEM');

-- 상태전이: 확정(잠금) / 해제(되돌리기) / 취소
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('CL', 'TMP', 'CONFIRM', 'CFM', '마감확정', 'FWD', 'N', 1, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('CL', 'CFM', 'UNLOCK', 'TMP', '마감해제', 'BWD', 'Y', 2, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('CL', 'TMP', 'CANCEL', 'CANCEL', '취소', 'END', 'Y', 9, 'SYSTEM');

-- 메뉴
INSERT INTO CM_MENU (MENU_ID, MENU_NM, UP_MENU_ID, MENU_LVL, URL, ICON, SORT_NO, REG_ID) VALUES ('PRO_CL', '정산/마감', 'PRO', 2, '/pro/cl', 'calculator', 4, 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('ADMIN', 'PRO_CL', 'MANAGEMENT', 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('USER', 'PRO_CL', 'SAVE', 'SYSTEM');

COMMIT;
