-- =============================================================
-- 구매시스템 DDL - 13. 견적(RFx / RFQ)
-- =============================================================

-- ---------- RX_RFX (견적 헤더) ----------
CREATE TABLE RX_RFX (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD     VARCHAR2(18 CHAR) NOT NULL,
  RFX_NO      VARCHAR2(30 CHAR) NOT NULL,
  RFX_TYP     VARCHAR2(18 CHAR) DEFAULT 'RFQ',
  RFX_TITLE   VARCHAR2(300 CHAR) NOT NULL,
  PURC_GRP_CD VARCHAR2(18 CHAR),
  CHRG_USR_ID VARCHAR2(18 CHAR),
  OPEN_YMD    DATE,
  CLOSE_YMD   DATE,
  EVAL_TYP    VARCHAR2(18 CHAR) DEFAULT 'PRICE',
  CURR_CD     VARCHAR2(3 CHAR) DEFAULT 'KRW',
  SRC_TYP     VARCHAR2(18 CHAR),
  SRC_ID      NUMBER,
  SEL_VD_CD   VARCHAR2(18 CHAR),
  SEL_VD_NM   VARCHAR2(200 CHAR),
  STS         VARCHAR2(18 CHAR) DEFAULT 'TMP' NOT NULL,
  REMARK      VARCHAR2(2000 CHAR),
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_RX_RFX_1 UNIQUE (COMP_CD, RFX_NO)
);
COMMENT ON TABLE RX_RFX IS '견적 헤더';
COMMENT ON COLUMN RX_RFX.RFX_TYP IS '견적유형(RFQ/RFP)';
COMMENT ON COLUMN RX_RFX.SEL_VD_CD IS '선정협력사';
COMMENT ON COLUMN RX_RFX.STS IS '진행상태(TMP/OPEN/SEL/CANCEL)';

-- ---------- RX_RFX_ITEM (견적 품목) ----------
CREATE TABLE RX_RFX_ITEM (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RFX_ID      NUMBER NOT NULL,
  LINE_NO     NUMBER NOT NULL,
  PR_ITEM_ID  NUMBER,
  ITEM_CD     VARCHAR2(18 CHAR),
  ITEM_NM     VARCHAR2(300 CHAR),
  SPEC        VARCHAR2(500 CHAR),
  UNIT_CD     VARCHAR2(18 CHAR),
  QTY         NUMBER(20,5) DEFAULT 0,
  BASE_PRC    NUMBER(20,5) DEFAULT 0,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_RX_RFX_ITEM_1 UNIQUE (RFX_ID, LINE_NO),
  CONSTRAINT FK_RX_RFX_ITEM_1 FOREIGN KEY (RFX_ID) REFERENCES RX_RFX (ID)
);
COMMENT ON TABLE RX_RFX_ITEM IS '견적 품목';

-- ---------- RX_RFX_VENDOR (초대 협력사 + 응답요약) ----------
CREATE TABLE RX_RFX_VENDOR (
  ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RFX_ID        NUMBER NOT NULL,
  VD_CD         VARCHAR2(18 CHAR) NOT NULL,
  VD_NM         VARCHAR2(200 CHAR),
  RESP_YN       CHAR(1 CHAR) DEFAULT 'N',
  SEL_YN        CHAR(1 CHAR) DEFAULT 'N',
  QUOTE_TOT_AMT NUMBER(20,5) DEFAULT 0,
  QUOTE_YMD     DATE,
  REG_ID        VARCHAR2(18 CHAR),
  REG_DT        TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_RX_RFX_VENDOR_1 UNIQUE (RFX_ID, VD_CD),
  CONSTRAINT FK_RX_RFX_VENDOR_1 FOREIGN KEY (RFX_ID) REFERENCES RX_RFX (ID)
);
COMMENT ON TABLE RX_RFX_VENDOR IS '견적 초대협력사/응답요약';
COMMENT ON COLUMN RX_RFX_VENDOR.RESP_YN IS '응답여부';
COMMENT ON COLUMN RX_RFX_VENDOR.SEL_YN IS '선정여부';

-- ---------- RX_QUOTE_ITEM (협력사 견적 품목 응답) ----------
CREATE TABLE RX_QUOTE_ITEM (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RFX_ID      NUMBER NOT NULL,
  VD_CD       VARCHAR2(18 CHAR) NOT NULL,
  RFX_ITEM_ID NUMBER NOT NULL,
  OFFER_PRC   NUMBER(20,5) DEFAULT 0,
  OFFER_AMT   NUMBER(20,5) DEFAULT 0,
  DLV_YMD     DATE,
  REMARK      VARCHAR2(500 CHAR),
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_RX_QUOTE_ITEM_1 UNIQUE (RFX_ID, VD_CD, RFX_ITEM_ID)
);
COMMENT ON TABLE RX_QUOTE_ITEM IS '협력사 견적 품목 응답';
COMMENT ON COLUMN RX_QUOTE_ITEM.OFFER_PRC IS '제시단가';
