-- =============================================================
-- 구매시스템 SEED - 14. 견적(RFx) 관련
-- =============================================================

INSERT INTO CM_CODE_GRP (GRP_CD, GRP_NM, DESCRIPTION, REG_ID) VALUES ('RFX_STS', '견적상태', 'RFx 진행상태', 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('RFX_STS', 'TMP', '작성중', 'Draft', 1, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('RFX_STS', 'OPEN', '공고중', 'Open', 2, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('RFX_STS', 'SEL', '선정완료', 'Selected', 3, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, CD_NM_EN, SORT_NO, REG_ID) VALUES ('RFX_STS', 'CANCEL', '유찰/취소', 'Canceled', 9, 'SYSTEM');

INSERT INTO CM_DOC_NO (DOC_TYP, DOC_NM, PREFIX, DATE_FMT, SEQ_LEN, LAST_SEQ, REG_ID)
VALUES ('RX', '견적', 'RX', 'YYYYMM', 4, 0, 'SYSTEM');

-- 상태전이: 공고 / 선정 / 선정취소(되돌리기) / 유찰·취소
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('RX', 'TMP', 'OPEN', 'OPEN', '공고', 'FWD', 'N', 1, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('RX', 'OPEN', 'SELECT', 'SEL', '선정', 'FWD', 'N', 1, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('RX', 'SEL', 'CANCEL_SEL', 'OPEN', '선정취소', 'BWD', 'Y', 2, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('RX', 'OPEN', 'CANCEL', 'CANCEL', '유찰', 'END', 'Y', 9, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('RX', 'TMP', 'CANCEL', 'CANCEL', '취소', 'END', 'Y', 9, 'SYSTEM');

-- 메뉴 (구매요청 다음, 발주 앞)
INSERT INTO CM_MENU (MENU_ID, MENU_NM, UP_MENU_ID, MENU_LVL, URL, ICON, SORT_NO, REG_ID) VALUES ('PRO_RX', '견적', 'PRO', 2, '/pro/rx', 'tag', 1.5, 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('ADMIN', 'PRO_RX', 'MANAGEMENT', 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('USER', 'PRO_RX', 'SAVE', 'SYSTEM');

COMMIT;
