-- =============================================================
-- 구매시스템 DDL - 17. 협력사 리스크 (감시 Audit / 규제준수 Regal)
-- =============================================================

-- ---------- VD_AUDIT (협력사 감시 헤더) ----------
CREATE TABLE VD_AUDIT (
  ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD      VARCHAR2(18 CHAR) NOT NULL,
  AUDIT_NO     VARCHAR2(30 CHAR) NOT NULL,
  VD_CD        VARCHAR2(18 CHAR),
  VD_NM        VARCHAR2(200 CHAR),
  AUDIT_TYP    VARCHAR2(18 CHAR) DEFAULT 'REGULAR',
  AUDIT_YMD    DATE,
  AUDITOR_ID   VARCHAR2(18 CHAR),
  RESULT_GRADE VARCHAR2(18 CHAR),
  FINDING_CNT  NUMBER DEFAULT 0,
  ACTION_REQ_YN CHAR(1 CHAR) DEFAULT 'N',
  STS          VARCHAR2(18 CHAR) DEFAULT 'ING' NOT NULL,
  REMARK       VARCHAR2(2000 CHAR),
  USE_YN       CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN       CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID       VARCHAR2(18 CHAR),
  REG_DT       TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID       VARCHAR2(18 CHAR),
  MOD_DT       TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_VD_AUDIT_1 UNIQUE (COMP_CD, AUDIT_NO)
);
COMMENT ON TABLE VD_AUDIT IS '협력사 감시';
COMMENT ON COLUMN VD_AUDIT.AUDIT_TYP IS '감시유형(REGULAR정기/SPECIAL특별)';
COMMENT ON COLUMN VD_AUDIT.RESULT_GRADE IS '종합결과(SAFE/WATCH/RISK)';
COMMENT ON COLUMN VD_AUDIT.STS IS '진행상태(ING/DONE/CANCEL)';

-- ---------- VD_AUDIT_RESULT (감시 항목 결과) ----------
CREATE TABLE VD_AUDIT_RESULT (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  AUDIT_ID    NUMBER NOT NULL,
  ITEM_SEQ    NUMBER NOT NULL,
  AUDIT_ITEM_NM VARCHAR2(300 CHAR),
  RESULT      VARCHAR2(18 CHAR) DEFAULT 'SAFE',
  FINDING     VARCHAR2(1000 CHAR),
  ACTION_REQ  VARCHAR2(1000 CHAR),
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_VD_AUDIT_RESULT_1 UNIQUE (AUDIT_ID, ITEM_SEQ),
  CONSTRAINT FK_VD_AUDIT_RESULT_1 FOREIGN KEY (AUDIT_ID) REFERENCES VD_AUDIT (ID)
);
COMMENT ON TABLE VD_AUDIT_RESULT IS '협력사 감시 항목결과';
COMMENT ON COLUMN VD_AUDIT_RESULT.RESULT IS '결과(SAFE양호/WATCH관찰/RISK위험)';
COMMENT ON COLUMN VD_AUDIT_RESULT.FINDING IS '지적사항';

-- ---------- VD_REGAL (규제/법령) ----------
CREATE TABLE VD_REGAL (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  REGAL_NO    VARCHAR2(30 CHAR) NOT NULL,
  REGAL_NM    VARCHAR2(300 CHAR) NOT NULL,
  REGAL_TYP   VARCHAR2(18 CHAR) DEFAULT 'LAW',
  PLAN_YMD    DATE,
  NOTIFY_YMD  DATE,
  ENFORCE_YMD DATE,
  TARGET_DESC VARCHAR2(2000 CHAR),
  ALARM_YN    CHAR(1 CHAR) DEFAULT 'N',
  ALARM_BEFORE_DAY NUMBER DEFAULT 30,
  STS         VARCHAR2(18 CHAR) DEFAULT 'ACTIVE',
  REMARK      VARCHAR2(1000 CHAR),
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_VD_REGAL_1 UNIQUE (REGAL_NO)
);
COMMENT ON TABLE VD_REGAL IS '규제/법령 정보';
COMMENT ON COLUMN VD_REGAL.REGAL_TYP IS '구분(LAW법/DECREE시행령/NOTICE고시/ETC)';
COMMENT ON COLUMN VD_REGAL.ENFORCE_YMD IS '시행일';
COMMENT ON COLUMN VD_REGAL.ALARM_BEFORE_DAY IS '시행 N일전 알림';
