-- =============================================================
-- 구매시스템 DDL - 19. 역경매(Auction)
-- =============================================================

-- ---------- AU_AUCTION (역경매 헤더) ----------
CREATE TABLE AU_AUCTION (
  ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD      VARCHAR2(18 CHAR) NOT NULL,
  AUCTION_NO   VARCHAR2(30 CHAR) NOT NULL,
  AUCTION_TITLE VARCHAR2(300 CHAR) NOT NULL,
  PURC_GRP_CD  VARCHAR2(18 CHAR),
  CHRG_USR_ID  VARCHAR2(18 CHAR),
  START_YMD    DATE,
  END_YMD      DATE,
  START_PRC    NUMBER(20,5) DEFAULT 0,
  MIN_DOWN_PRC NUMBER(20,5) DEFAULT 0,
  CURR_CD      VARCHAR2(3 CHAR) DEFAULT 'KRW',
  SRC_TYP      VARCHAR2(18 CHAR),
  SRC_ID       NUMBER,
  AWARD_VD_CD  VARCHAR2(18 CHAR),
  AWARD_VD_NM  VARCHAR2(200 CHAR),
  AWARD_AMT    NUMBER(20,5),
  STS          VARCHAR2(18 CHAR) DEFAULT 'TMP' NOT NULL,
  REMARK       VARCHAR2(2000 CHAR),
  USE_YN       CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN       CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID       VARCHAR2(18 CHAR),
  REG_DT       TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID       VARCHAR2(18 CHAR),
  MOD_DT       TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_AU_AUCTION_1 UNIQUE (COMP_CD, AUCTION_NO)
);
COMMENT ON TABLE AU_AUCTION IS '역경매 헤더';
COMMENT ON COLUMN AU_AUCTION.START_PRC IS '시작가(상한 총액)';
COMMENT ON COLUMN AU_AUCTION.MIN_DOWN_PRC IS '최소 하향폭';
COMMENT ON COLUMN AU_AUCTION.STS IS '진행상태(TMP/OPEN/AWARD/CANCEL)';

-- ---------- AU_AUCTION_ITEM (역경매 품목) ----------
CREATE TABLE AU_AUCTION_ITEM (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  AUCTION_ID  NUMBER NOT NULL,
  LINE_NO     NUMBER NOT NULL,
  PR_ITEM_ID  NUMBER,
  ITEM_CD     VARCHAR2(18 CHAR),
  ITEM_NM     VARCHAR2(300 CHAR),
  SPEC        VARCHAR2(500 CHAR),
  UNIT_CD     VARCHAR2(18 CHAR),
  QTY         NUMBER(20,5) DEFAULT 0,
  START_PRC   NUMBER(20,5) DEFAULT 0,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_AU_AUCTION_ITEM_1 UNIQUE (AUCTION_ID, LINE_NO),
  CONSTRAINT FK_AU_AUCTION_ITEM_1 FOREIGN KEY (AUCTION_ID) REFERENCES AU_AUCTION (ID)
);
COMMENT ON TABLE AU_AUCTION_ITEM IS '역경매 품목';

-- ---------- AU_AUCTION_VENDOR (참여 협력사/현황) ----------
CREATE TABLE AU_AUCTION_VENDOR (
  ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  AUCTION_ID   NUMBER NOT NULL,
  VD_CD        VARCHAR2(18 CHAR) NOT NULL,
  VD_NM        VARCHAR2(200 CHAR),
  JOIN_YN      CHAR(1 CHAR) DEFAULT 'N',
  AWARD_YN     CHAR(1 CHAR) DEFAULT 'N',
  LAST_BID_AMT NUMBER(20,5),
  BID_CNT      NUMBER DEFAULT 0,
  REG_ID       VARCHAR2(18 CHAR),
  REG_DT       TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_AU_AUCTION_VENDOR_1 UNIQUE (AUCTION_ID, VD_CD),
  CONSTRAINT FK_AU_AUCTION_VENDOR_1 FOREIGN KEY (AUCTION_ID) REFERENCES AU_AUCTION (ID)
);
COMMENT ON TABLE AU_AUCTION_VENDOR IS '역경매 참여협력사';
COMMENT ON COLUMN AU_AUCTION_VENDOR.LAST_BID_AMT IS '최종 입찰가';

-- ---------- AU_BID (입찰 내역, 이력성) ----------
CREATE TABLE AU_BID (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  AUCTION_ID NUMBER NOT NULL,
  VD_CD      VARCHAR2(18 CHAR) NOT NULL,
  VD_NM      VARCHAR2(200 CHAR),
  BID_AMT    NUMBER(20,5) NOT NULL,
  BID_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  RANK_NO    NUMBER,
  REG_ID     VARCHAR2(18 CHAR)
);
COMMENT ON TABLE AU_BID IS '역경매 입찰내역';
CREATE INDEX IX_AU_BID_1 ON AU_BID (AUCTION_ID, BID_DT);
