-- =============================================================
-- 구매시스템 SEED - 20. 역경매 관련
-- =============================================================

INSERT INTO CM_CODE_GRP (GRP_CD, GRP_NM, REG_ID) VALUES ('AUCTION_STS', '역경매상태', 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('AUCTION_STS', 'TMP', '작성중', 1, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('AUCTION_STS', 'OPEN', '진행중', 2, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('AUCTION_STS', 'AWARD', '낙찰', 3, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('AUCTION_STS', 'CANCEL', '유찰/취소', 9, 'SYSTEM');

INSERT INTO CM_DOC_NO (DOC_TYP, DOC_NM, PREFIX, DATE_FMT, SEQ_LEN, LAST_SEQ, REG_ID)
VALUES ('AC', '역경매', 'AC', 'YYYYMM', 4, 0, 'SYSTEM');

-- 상태전이: 시작 / 낙찰 / 낙찰취소(되돌리기) / 유찰
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('AC', 'TMP', 'OPEN', 'OPEN', '경매시작', 'FWD', 'N', 1, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('AC', 'OPEN', 'AWARD', 'AWARD', '낙찰', 'FWD', 'N', 1, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('AC', 'AWARD', 'CANCEL_AWARD', 'OPEN', '낙찰취소', 'BWD', 'Y', 2, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('AC', 'OPEN', 'CANCEL', 'CANCEL', '유찰', 'END', 'Y', 9, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('AC', 'TMP', 'CANCEL', 'CANCEL', '취소', 'END', 'Y', 9, 'SYSTEM');

-- 메뉴 (견적 다음)
INSERT INTO CM_MENU (MENU_ID, MENU_NM, UP_MENU_ID, MENU_LVL, URL, ICON, SORT_NO, REG_ID) VALUES ('PRO_AU', '역경매', 'PRO', 2, '/pro/au', 'gavel', 1.7, 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('ADMIN', 'PRO_AU', 'MANAGEMENT', 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('USER', 'PRO_AU', 'SAVE', 'SYSTEM');

COMMIT;
