-- =============================================================
-- 구매시스템 DDL - 21. 전자결재 엔진 (결재 + 결재선)
-- =============================================================

-- ---------- AP_APPROVAL (결재 마스터) ----------
CREATE TABLE AP_APPROVAL (
  ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD      VARCHAR2(18 CHAR) NOT NULL,
  APRV_NO      VARCHAR2(30 CHAR) NOT NULL,
  DOC_TYP      VARCHAR2(18 CHAR) NOT NULL,
  DOC_ID       NUMBER NOT NULL,
  DOC_NO       VARCHAR2(30 CHAR),
  APRV_TITLE   VARCHAR2(300 CHAR),
  DRAFT_USR_ID VARCHAR2(18 CHAR),
  DRAFT_USR_NM VARCHAR2(100 CHAR),
  DRAFT_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CUR_STEP_NO  NUMBER DEFAULT 1,
  APRV_STS     VARCHAR2(18 CHAR) DEFAULT 'ING' NOT NULL,
  FINAL_APRV_DT TIMESTAMP(0) WITH LOCAL TIME ZONE,
  USE_YN       CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN       CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID       VARCHAR2(18 CHAR),
  REG_DT       TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID       VARCHAR2(18 CHAR),
  MOD_DT       TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_AP_APPROVAL_1 UNIQUE (COMP_CD, APRV_NO)
);
COMMENT ON TABLE AP_APPROVAL IS '전자결재 마스터';
COMMENT ON COLUMN AP_APPROVAL.DOC_TYP IS '원문서유형(PR/PO 등)';
COMMENT ON COLUMN AP_APPROVAL.CUR_STEP_NO IS '현재 결재단계';
COMMENT ON COLUMN AP_APPROVAL.APRV_STS IS '결재상태(ING/DONE/REJECT/RECALL)';
CREATE INDEX IX_AP_APPROVAL_1 ON AP_APPROVAL (DOC_TYP, DOC_ID);

-- ---------- AP_APPROVAL_LINE (결재선) ----------
CREATE TABLE AP_APPROVAL_LINE (
  ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  APRV_ID      NUMBER NOT NULL,
  STEP_NO      NUMBER NOT NULL,
  APRV_USR_ID  VARCHAR2(18 CHAR) NOT NULL,
  APRV_USR_NM  VARCHAR2(100 CHAR),
  LINE_STS     VARCHAR2(18 CHAR) DEFAULT 'WAIT' NOT NULL,
  APRV_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE,
  OPINION      VARCHAR2(1000 CHAR),
  REG_ID       VARCHAR2(18 CHAR),
  REG_DT       TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_AP_APPROVAL_LINE_1 UNIQUE (APRV_ID, STEP_NO),
  CONSTRAINT FK_AP_APPROVAL_LINE_1 FOREIGN KEY (APRV_ID) REFERENCES AP_APPROVAL (ID)
);
COMMENT ON TABLE AP_APPROVAL_LINE IS '결재선';
COMMENT ON COLUMN AP_APPROVAL_LINE.LINE_STS IS '단계상태(WAIT대기/ING진행/APPROVE승인/REJECT반려)';
CREATE INDEX IX_AP_APPROVAL_LINE_1 ON AP_APPROVAL_LINE (APRV_USR_ID, LINE_STS);
