-- =============================================================
-- 구매시스템 DDL - 23. 품질관리(QLT) - 입고검사
-- =============================================================

-- ---------- QL_INSPECTION (입고검사 헤더) ----------
CREATE TABLE QL_INSPECTION (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD     VARCHAR2(18 CHAR) NOT NULL,
  INSP_NO     VARCHAR2(30 CHAR) NOT NULL,
  GR_ID       NUMBER,
  GR_NO       VARCHAR2(30 CHAR),
  PO_NO       VARCHAR2(30 CHAR),
  VD_CD       VARCHAR2(18 CHAR),
  VD_NM       VARCHAR2(200 CHAR),
  OPER_ORG_CD VARCHAR2(18 CHAR),
  INSP_TYP    VARCHAR2(18 CHAR) DEFAULT 'INCOMING',
  QM_LOT_NO   VARCHAR2(30 CHAR),
  INSP_QTY    NUMBER(20,5) DEFAULT 0,
  INSP_RESULT VARCHAR2(18 CHAR),
  INSP_YMD    DATE,
  INSP_USR_ID VARCHAR2(18 CHAR),
  STS         VARCHAR2(18 CHAR) DEFAULT 'ING' NOT NULL,
  IF_STATUS   CHAR(1 CHAR) DEFAULT 'N',
  REMARK      VARCHAR2(2000 CHAR),
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_QL_INSPECTION_1 UNIQUE (COMP_CD, INSP_NO)
);
COMMENT ON TABLE QL_INSPECTION IS '입고검사 헤더';
COMMENT ON COLUMN QL_INSPECTION.QM_LOT_NO IS 'SAP QM 검사로트번호';
COMMENT ON COLUMN QL_INSPECTION.INSP_RESULT IS '검사결과(PASS/FAIL/PARTIAL)';
COMMENT ON COLUMN QL_INSPECTION.STS IS '진행상태(ING/DONE/CANCEL)';

-- ---------- QL_INSPECTION_RESULT (검사 항목결과) ----------
CREATE TABLE QL_INSPECTION_RESULT (
  ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  INSP_ID      NUMBER NOT NULL,
  ITEM_SEQ     NUMBER NOT NULL,
  INSP_ITEM_NM VARCHAR2(200 CHAR),
  SPEC_VAL     VARCHAR2(100 CHAR),
  MEASURE_VAL  VARCHAR2(100 CHAR),
  UNIT         VARCHAR2(18 CHAR),
  PASS_YN      CHAR(1 CHAR) DEFAULT 'Y',
  QM_CODE      VARCHAR2(30 CHAR),
  REMARK       VARCHAR2(500 CHAR),
  REG_ID       VARCHAR2(18 CHAR),
  REG_DT       TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_QL_INSPECTION_RESULT_1 UNIQUE (INSP_ID, ITEM_SEQ),
  CONSTRAINT FK_QL_INSPECTION_RESULT_1 FOREIGN KEY (INSP_ID) REFERENCES QL_INSPECTION (ID)
);
COMMENT ON TABLE QL_INSPECTION_RESULT IS '입고검사 항목결과';
COMMENT ON COLUMN QL_INSPECTION_RESULT.SPEC_VAL IS '규격(기준)값';
COMMENT ON COLUMN QL_INSPECTION_RESULT.MEASURE_VAL IS '측정값';
