-- =============================================================
-- 구매시스템 DDL - 27. 단가계약(CT)
-- =============================================================

CREATE TABLE CT_CONTRACT (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD     VARCHAR2(18 CHAR) NOT NULL,
  CT_NO       VARCHAR2(30 CHAR) NOT NULL,
  CT_REV      NUMBER DEFAULT 0,
  CT_TITLE    VARCHAR2(300 CHAR) NOT NULL,
  CT_TYP      VARCHAR2(18 CHAR) DEFAULT 'PRICE',
  VD_CD       VARCHAR2(18 CHAR),
  VD_NM       VARCHAR2(200 CHAR),
  PURC_GRP_CD VARCHAR2(18 CHAR),
  CHRG_USR_ID VARCHAR2(18 CHAR),
  VALID_SD    DATE,
  VALID_ED    DATE,
  CURR_CD     VARCHAR2(3 CHAR) DEFAULT 'KRW',
  SUPL_AMT    NUMBER(20,5) DEFAULT 0,
  VAT_AMT     NUMBER(20,5) DEFAULT 0,
  TOT_AMT     NUMBER(20,5) DEFAULT 0,
  SRC_TYP     VARCHAR2(18 CHAR),
  SRC_ID      NUMBER,
  STS         VARCHAR2(18 CHAR) DEFAULT 'TMP' NOT NULL,
  IF_STATUS   CHAR(1 CHAR) DEFAULT 'N',
  REMARK      VARCHAR2(2000 CHAR),
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_CT_CONTRACT_1 UNIQUE (COMP_CD, CT_NO)
);
COMMENT ON TABLE CT_CONTRACT IS '단가계약 헤더';
COMMENT ON COLUMN CT_CONTRACT.CT_TYP IS '계약유형(PRICE 단가계약)';
COMMENT ON COLUMN CT_CONTRACT.STS IS '진행상태(TMP/REQ/ACTIVE/EXPIRE/TERMINATE/CANCEL)';

CREATE TABLE CT_CONTRACT_ITEM (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CONTRACT_ID NUMBER NOT NULL,
  LINE_NO     NUMBER NOT NULL,
  ITEM_CD     VARCHAR2(18 CHAR),
  ITEM_NM     VARCHAR2(300 CHAR),
  SPEC        VARCHAR2(500 CHAR),
  UNIT_CD     VARCHAR2(18 CHAR),
  CT_PRC      NUMBER(20,5) DEFAULT 0,
  APPLY_SD    DATE,
  APPLY_ED    DATE,
  MIN_QTY     NUMBER(20,5) DEFAULT 0,
  MAX_QTY     NUMBER(20,5) DEFAULT 0,
  REMARK      VARCHAR2(1000 CHAR),
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_CT_CONTRACT_ITEM_1 UNIQUE (CONTRACT_ID, LINE_NO),
  CONSTRAINT FK_CT_CONTRACT_ITEM_1 FOREIGN KEY (CONTRACT_ID) REFERENCES CT_CONTRACT (ID)
);
COMMENT ON TABLE CT_CONTRACT_ITEM IS '단가계약 품목';
COMMENT ON COLUMN CT_CONTRACT_ITEM.CT_PRC IS '계약단가';
COMMENT ON COLUMN CT_CONTRACT_ITEM.APPLY_SD IS '단가 적용 시작일';
CREATE INDEX IX_CT_CONTRACT_ITEM_1 ON CT_CONTRACT_ITEM (ITEM_CD);
