-- =============================================================
-- 구매시스템 DDL - 29. 품목단가 구간관리(IP)
--   IP_ITEM_PRICE : 확정 단가구간 (품목·협력사별 비중첩 기간 세그먼트)
--   IP_PRICE_RSV  : 단가 변경예약 헤더(번들) - 결재 후 적용
--   IP_PRICE_RSV_LINE : 변경예약 명세
--   IP_PRICE_HIS  : 구간분할 변경이력 (당김/삽입/복원/삭제)
-- =============================================================

CREATE TABLE IP_ITEM_PRICE (
  ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD   VARCHAR2(18 CHAR) NOT NULL,
  VD_CD     VARCHAR2(18 CHAR) NOT NULL,
  VD_NM     VARCHAR2(200 CHAR),
  ITEM_CD   VARCHAR2(18 CHAR) NOT NULL,
  ITEM_NM   VARCHAR2(300 CHAR),
  UNIT_CD   VARCHAR2(18 CHAR),
  CURR_CD   VARCHAR2(3 CHAR) DEFAULT 'KRW',
  APPLY_SD  DATE NOT NULL,
  APPLY_ED  DATE NOT NULL,
  UNIT_PRC  NUMBER(20,5) DEFAULT 0,
  SRC_TYP   VARCHAR2(18 CHAR),     -- RSV(변경예약)/CT(계약)/MANUAL
  SRC_ID    NUMBER,                -- 출처 문서 ID (예약 LINE ID)
  REMARK    VARCHAR2(1000 CHAR),
  USE_YN    CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN    CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID    VARCHAR2(18 CHAR),
  REG_DT    TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID    VARCHAR2(18 CHAR),
  MOD_DT    TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE IP_ITEM_PRICE IS '품목 확정단가 구간';
COMMENT ON COLUMN IP_ITEM_PRICE.APPLY_SD IS '적용 시작일';
COMMENT ON COLUMN IP_ITEM_PRICE.APPLY_ED IS '적용 종료일';
COMMENT ON COLUMN IP_ITEM_PRICE.SRC_TYP IS '출처(RSV/CT/MANUAL)';
CREATE INDEX IX_IP_ITEM_PRICE_1 ON IP_ITEM_PRICE (COMP_CD, VD_CD, ITEM_CD, APPLY_SD);

CREATE TABLE IP_PRICE_RSV (
  ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD   VARCHAR2(18 CHAR) NOT NULL,
  RSV_NO    VARCHAR2(30 CHAR) NOT NULL,
  RSV_TITLE VARCHAR2(300 CHAR) NOT NULL,
  VD_CD     VARCHAR2(18 CHAR),
  VD_NM     VARCHAR2(200 CHAR),
  CHRG_USR_ID VARCHAR2(18 CHAR),
  APPLY_DT  DATE,                  -- 적용 예정일(참고)
  STS       VARCHAR2(18 CHAR) DEFAULT 'TMP' NOT NULL,  -- TMP/REQ/APPLIED/CANCEL
  REMARK    VARCHAR2(2000 CHAR),
  USE_YN    CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN    CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID    VARCHAR2(18 CHAR),
  REG_DT    TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID    VARCHAR2(18 CHAR),
  MOD_DT    TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_IP_PRICE_RSV_1 UNIQUE (COMP_CD, RSV_NO)
);
COMMENT ON TABLE IP_PRICE_RSV IS '단가 변경예약 헤더';
COMMENT ON COLUMN IP_PRICE_RSV.STS IS '상태(TMP/REQ/APPLIED/CANCEL)';

CREATE TABLE IP_PRICE_RSV_LINE (
  ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RSV_ID    NUMBER NOT NULL,
  LINE_NO   NUMBER NOT NULL,
  ITEM_CD   VARCHAR2(18 CHAR),
  ITEM_NM   VARCHAR2(300 CHAR),
  UNIT_CD   VARCHAR2(18 CHAR),
  APPLY_SD  DATE,
  APPLY_ED  DATE,
  UNIT_PRC  NUMBER(20,5) DEFAULT 0,
  REMARK    VARCHAR2(1000 CHAR),
  REG_ID    VARCHAR2(18 CHAR),
  REG_DT    TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_IP_PRICE_RSV_LINE_1 UNIQUE (RSV_ID, LINE_NO),
  CONSTRAINT FK_IP_PRICE_RSV_LINE_1 FOREIGN KEY (RSV_ID) REFERENCES IP_PRICE_RSV (ID)
);
COMMENT ON TABLE IP_PRICE_RSV_LINE IS '단가 변경예약 명세';

CREATE TABLE IP_PRICE_HIS (
  ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD   VARCHAR2(18 CHAR),
  VD_CD     VARCHAR2(18 CHAR),
  ITEM_CD   VARCHAR2(18 CHAR),
  CHG_TYP   VARCHAR2(18 CHAR),     -- PULL(앞구간당김)/INSERT(신규삽입)/RESTORE(잔여복원)/DELETE(구간삭제)/TAIL(뒷구간당김)
  OLD_SD    VARCHAR2(10 CHAR),
  OLD_ED    VARCHAR2(10 CHAR),
  OLD_PRC   NUMBER(20,5),
  NEW_SD    VARCHAR2(10 CHAR),
  NEW_ED    VARCHAR2(10 CHAR),
  NEW_PRC   NUMBER(20,5),
  SRC_TYP   VARCHAR2(18 CHAR),     -- RSV
  SRC_ID    NUMBER,                -- 예약 LINE ID
  REG_ID    VARCHAR2(18 CHAR),
  REG_DT    TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE IP_PRICE_HIS IS '단가 구간분할 변경이력';
COMMENT ON COLUMN IP_PRICE_HIS.CHG_TYP IS 'PULL/INSERT/RESTORE/DELETE/TAIL';
CREATE INDEX IX_IP_PRICE_HIS_1 ON IP_PRICE_HIS (VD_CD, ITEM_CD);
