-- =============================================================
-- 구매시스템 DDL - 31. 갭정산(정산 조정 자동집계)
--   CL_ADJ_RATE  : 조정율 마스터 (협력사/조정유형별 요율·단가)
--   CL_CLOSE_ADJ : 정산 조정명세 (자동계산 결과)
--   CL_CLOSE 확장: ADJ_AMT(조정합계), NET_AMT(최종 정산액)
-- =============================================================

ALTER TABLE CL_CLOSE ADD (ADJ_AMT NUMBER(20,5) DEFAULT 0);
ALTER TABLE CL_CLOSE ADD (NET_AMT NUMBER(20,5) DEFAULT 0);
COMMENT ON COLUMN CL_CLOSE.ADJ_AMT IS '조정합계(수수료/장려금 가감)';
COMMENT ON COLUMN CL_CLOSE.NET_AMT IS '최종 정산액(TOT_AMT + ADJ_AMT)';

CREATE TABLE CL_ADJ_RATE (
  ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD   VARCHAR2(18 CHAR) NOT NULL,
  VD_CD     VARCHAR2(18 CHAR),         -- NULL=전협력사 공통
  ADJ_TYP   VARCHAR2(18 CHAR) NOT NULL, -- LOGI_FEE/PICK_FEE/PURC_RBT/PROMO_RBT/BID_RBT
  CALC_BASE VARCHAR2(18 CHAR) DEFAULT 'SUPL', -- SUPL(공급가)/CNT(입고건수)/FIXED(정액)
  RATE      NUMBER(12,6) DEFAULT 0,     -- 요율(공급가 기준, 예 0.015=1.5%)
  UNIT_AMT  NUMBER(20,5) DEFAULT 0,     -- 건당/정액 금액
  SIGN_TYP  CHAR(1 CHAR) DEFAULT '-',   -- +(가산)/-(차감)
  VALID_SD  DATE,
  VALID_ED  DATE,
  REMARK    VARCHAR2(1000 CHAR),
  USE_YN    CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN    CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID    VARCHAR2(18 CHAR),
  REG_DT    TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID    VARCHAR2(18 CHAR),
  MOD_DT    TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE CL_ADJ_RATE IS '정산 조정율 마스터';
COMMENT ON COLUMN CL_ADJ_RATE.ADJ_TYP IS '조정유형(LOGI_FEE/PICK_FEE/PURC_RBT/PROMO_RBT/BID_RBT)';
COMMENT ON COLUMN CL_ADJ_RATE.CALC_BASE IS '계산기준(SUPL/CNT/FIXED)';
COMMENT ON COLUMN CL_ADJ_RATE.SIGN_TYP IS '부호(+가산/-차감)';
CREATE INDEX IX_CL_ADJ_RATE_1 ON CL_ADJ_RATE (COMP_CD, VD_CD, ADJ_TYP);

CREATE TABLE CL_CLOSE_ADJ (
  ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CLOSE_ID  NUMBER NOT NULL,
  LINE_NO   NUMBER NOT NULL,
  ADJ_TYP   VARCHAR2(18 CHAR),
  CALC_BASE VARCHAR2(18 CHAR),
  BASE_AMT  NUMBER(20,5) DEFAULT 0,   -- 계산 기준값(공급가 또는 건수)
  RATE      NUMBER(12,6) DEFAULT 0,
  UNIT_AMT  NUMBER(20,5) DEFAULT 0,
  SIGN_TYP  CHAR(1 CHAR) DEFAULT '-',
  ADJ_AMT   NUMBER(20,5) DEFAULT 0,   -- 부호반영 조정금액
  REMARK    VARCHAR2(1000 CHAR),
  REG_ID    VARCHAR2(18 CHAR),
  REG_DT    TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_CL_CLOSE_ADJ_1 UNIQUE (CLOSE_ID, LINE_NO),
  CONSTRAINT FK_CL_CLOSE_ADJ_1 FOREIGN KEY (CLOSE_ID) REFERENCES CL_CLOSE (ID)
);
COMMENT ON TABLE CL_CLOSE_ADJ IS '정산 조정명세(자동계산)';
CREATE INDEX IX_CL_CLOSE_ADJ_1 ON CL_CLOSE_ADJ (CLOSE_ID);
