-- =============================================================
-- 구매시스템 SEED - 32. 갭정산
-- =============================================================

-- 조정유형
INSERT INTO CM_CODE_GRP (GRP_CD, GRP_NM, REG_ID) VALUES ('CL_ADJ_TYP', '정산 조정유형', 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('CL_ADJ_TYP', 'LOGI_FEE', '물류수수료', 1, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('CL_ADJ_TYP', 'PICK_FEE', '피킹료', 2, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('CL_ADJ_TYP', 'PURC_RBT', '매입장려금', 3, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('CL_ADJ_TYP', 'PROMO_RBT', '판촉장려금', 4, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('CL_ADJ_TYP', 'BID_RBT', '입찰차이장려금', 5, 'SYSTEM');

-- 계산기준
INSERT INTO CM_CODE_GRP (GRP_CD, GRP_NM, REG_ID) VALUES ('CL_CALC_BASE', '정산 조정 계산기준', 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('CL_CALC_BASE', 'SUPL', '공급가 기준(요율)', 1, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('CL_CALC_BASE', 'CNT', '입고건수 기준(건당)', 2, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('CL_CALC_BASE', 'FIXED', '정액', 3, 'SYSTEM');

-- 샘플 조정율 (전협력사 공통: 물류수수료 1.5%, 피킹료 건당 5000, 매입장려금 2%)
INSERT INTO CL_ADJ_RATE (COMP_CD, VD_CD, ADJ_TYP, CALC_BASE, RATE, UNIT_AMT, SIGN_TYP, VALID_SD, VALID_ED, REMARK, REG_ID)
VALUES ('1000', NULL, 'LOGI_FEE', 'SUPL', 0.015, 0, '-', TO_DATE('2026-01-01','YYYY-MM-DD'), TO_DATE('2099-12-31','YYYY-MM-DD'), '공통 물류수수료 1.5%', 'SYSTEM');
INSERT INTO CL_ADJ_RATE (COMP_CD, VD_CD, ADJ_TYP, CALC_BASE, RATE, UNIT_AMT, SIGN_TYP, VALID_SD, VALID_ED, REMARK, REG_ID)
VALUES ('1000', NULL, 'PICK_FEE', 'CNT', 0, 5000, '-', TO_DATE('2026-01-01','YYYY-MM-DD'), TO_DATE('2099-12-31','YYYY-MM-DD'), '공통 피킹료 건당 5,000', 'SYSTEM');
INSERT INTO CL_ADJ_RATE (COMP_CD, VD_CD, ADJ_TYP, CALC_BASE, RATE, UNIT_AMT, SIGN_TYP, VALID_SD, VALID_ED, REMARK, REG_ID)
VALUES ('1000', 'VD-00001', 'PURC_RBT', 'SUPL', 0.02, 0, '-', TO_DATE('2026-01-01','YYYY-MM-DD'), TO_DATE('2099-12-31','YYYY-MM-DD'), 'VD-00001 매입장려금 2%', 'SYSTEM');

-- 조정율 마스터 메뉴
INSERT INTO CM_MENU (MENU_ID, MENU_NM, UP_MENU_ID, MENU_LVL, URL, ICON, SORT_NO, REG_ID) VALUES ('PRO_CLADJ', '정산조정율', 'PRO', 2, '/pro/cladj', 'percent', 5.5, 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('ADMIN', 'PRO_CLADJ', 'MANAGEMENT', 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('USER', 'PRO_CLADJ', 'SAVE', 'SYSTEM');

COMMIT;
