-- =============================================================
-- 구매시스템 DDL - 33. 결재엔진 고도화
--   결재유형(LINE_TYP): APRV결재 / AGRE합의 / REFR참조
--   전결: 결재선 FINAL_YN, 단계상태 SKIP(전결로 생략)
--   위임/대결: AP_DELEGATE
--   결재선 템플릿(금액조건별): AP_LINE_TPL + AP_LINE_TPL_STEP
-- =============================================================

ALTER TABLE AP_APPROVAL_LINE ADD (LINE_TYP VARCHAR2(18 CHAR) DEFAULT 'APRV');
ALTER TABLE AP_APPROVAL_LINE ADD (FINAL_YN CHAR(1 CHAR) DEFAULT 'N');
ALTER TABLE AP_APPROVAL_LINE ADD (ACT_AS_USR_ID VARCHAR2(18 CHAR));  -- 대결 처리자
COMMENT ON COLUMN AP_APPROVAL_LINE.LINE_TYP IS '결재유형(APRV결재/AGRE합의/REFR참조)';
COMMENT ON COLUMN AP_APPROVAL_LINE.FINAL_YN IS '전결권 보유(Y)';
COMMENT ON COLUMN AP_APPROVAL_LINE.ACT_AS_USR_ID IS '대결 처리자(위임)';

-- ---------- AP_DELEGATE (결재 위임/대결) ----------
CREATE TABLE AP_DELEGATE (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD     VARCHAR2(18 CHAR) NOT NULL,
  FROM_USR_ID VARCHAR2(18 CHAR) NOT NULL,  -- 위임자(원 결재자)
  FROM_USR_NM VARCHAR2(100 CHAR),
  TO_USR_ID   VARCHAR2(18 CHAR) NOT NULL,  -- 대결자(수임자)
  TO_USR_NM   VARCHAR2(100 CHAR),
  VALID_SD    DATE,
  VALID_ED    DATE,
  REMARK      VARCHAR2(500 CHAR),
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE AP_DELEGATE IS '결재 위임/대결';
CREATE INDEX IX_AP_DELEGATE_1 ON AP_DELEGATE (TO_USR_ID, USE_YN);
CREATE INDEX IX_AP_DELEGATE_2 ON AP_DELEGATE (FROM_USR_ID, USE_YN);

-- ---------- AP_LINE_TPL (결재선 템플릿 헤더, 금액조건별) ----------
CREATE TABLE AP_LINE_TPL (
  ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD   VARCHAR2(18 CHAR) NOT NULL,
  DOC_TYP   VARCHAR2(18 CHAR) NOT NULL,
  TPL_NM    VARCHAR2(200 CHAR) NOT NULL,
  AMT_FROM  NUMBER(20,5) DEFAULT 0,
  AMT_TO    NUMBER(20,5) DEFAULT 999999999999,
  SORT_NO   NUMBER DEFAULT 1,
  USE_YN    CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN    CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID    VARCHAR2(18 CHAR),
  REG_DT    TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID    VARCHAR2(18 CHAR),
  MOD_DT    TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE AP_LINE_TPL IS '결재선 템플릿(금액조건별)';
COMMENT ON COLUMN AP_LINE_TPL.AMT_FROM IS '적용 금액 하한';
COMMENT ON COLUMN AP_LINE_TPL.AMT_TO IS '적용 금액 상한';
CREATE INDEX IX_AP_LINE_TPL_1 ON AP_LINE_TPL (COMP_CD, DOC_TYP);

CREATE TABLE AP_LINE_TPL_STEP (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TPL_ID      NUMBER NOT NULL,
  STEP_NO     NUMBER NOT NULL,
  LINE_TYP    VARCHAR2(18 CHAR) DEFAULT 'APRV',
  APRV_USR_ID VARCHAR2(18 CHAR),
  APRV_USR_NM VARCHAR2(100 CHAR),
  FINAL_YN    CHAR(1 CHAR) DEFAULT 'N',
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_AP_LINE_TPL_STEP_1 UNIQUE (TPL_ID, STEP_NO),
  CONSTRAINT FK_AP_LINE_TPL_STEP_1 FOREIGN KEY (TPL_ID) REFERENCES AP_LINE_TPL (ID)
);
COMMENT ON TABLE AP_LINE_TPL_STEP IS '결재선 템플릿 단계';
