-- =============================================================
-- 구매시스템 SEED - 34. 결재엔진 고도화
-- =============================================================

-- 결재유형 코드
INSERT INTO CM_CODE_GRP (GRP_CD, GRP_NM, REG_ID) VALUES ('AP_LINE_TYP', '결재선 유형', 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('AP_LINE_TYP', 'APRV', '결재', 1, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('AP_LINE_TYP', 'AGRE', '합의', 2, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('AP_LINE_TYP', 'REFR', '참조', 3, 'SYSTEM');

-- 결재선 단계 상태 보강 (기존 LINE_STS 그룹: WAIT/ING/APPROVE/REJECT 에 추가)
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('LINE_STS', 'AGREE', '합의완료', 5, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('LINE_STS', 'FINAL', '전결', 6, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('LINE_STS', 'SKIP', '전결생략', 7, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('LINE_STS', 'REFER', '참조', 8, 'SYSTEM');

-- 위임/대결 메뉴
INSERT INTO CM_MENU (MENU_ID, MENU_NM, UP_MENU_ID, MENU_LVL, URL, ICON, SORT_NO, REG_ID) VALUES ('APR_DELEG', '결재 위임/대결', 'APRV', 2, '/approval/delegate', 'user-check', 3.1, 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('ADMIN', 'APR_DELEG', 'MANAGEMENT', 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('USER', 'APR_DELEG', 'SAVE', 'SYSTEM');

-- 결재선 템플릿 메뉴
INSERT INTO CM_MENU (MENU_ID, MENU_NM, UP_MENU_ID, MENU_LVL, URL, ICON, SORT_NO, REG_ID) VALUES ('APR_TPL', '결재선 템플릿', 'APRV', 2, '/approval/template', 'list', 3.2, 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('ADMIN', 'APR_TPL', 'MANAGEMENT', 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('USER', 'APR_TPL', 'SAVE', 'SYSTEM');

-- 샘플 결재선 템플릿 (발주 PO: 1천만 미만 1단계, 1천만 이상 2단계+전결)
INSERT INTO AP_LINE_TPL (COMP_CD, DOC_TYP, TPL_NM, AMT_FROM, AMT_TO, SORT_NO, REG_ID)
VALUES ('1000', 'PO', '발주 소액(1천만 미만)', 0, 9999999, 1, 'SYSTEM');
INSERT INTO AP_LINE_TPL_STEP (TPL_ID, STEP_NO, LINE_TYP, APRV_USR_ID, APRV_USR_NM, FINAL_YN, REG_ID)
VALUES ((SELECT ID FROM AP_LINE_TPL WHERE COMP_CD='1000' AND DOC_TYP='PO' AND TPL_NM='발주 소액(1천만 미만)'), 1, 'APRV', 'admin', '시스템관리자', 'Y', 'SYSTEM');

INSERT INTO AP_LINE_TPL (COMP_CD, DOC_TYP, TPL_NM, AMT_FROM, AMT_TO, SORT_NO, REG_ID)
VALUES ('1000', 'PO', '발주 고액(1천만 이상)', 10000000, 999999999999, 2, 'SYSTEM');
INSERT INTO AP_LINE_TPL_STEP (TPL_ID, STEP_NO, LINE_TYP, APRV_USR_ID, APRV_USR_NM, FINAL_YN, REG_ID)
VALUES ((SELECT ID FROM AP_LINE_TPL WHERE COMP_CD='1000' AND DOC_TYP='PO' AND TPL_NM='발주 고액(1천만 이상)'), 1, 'AGRE', 'admin', '시스템관리자', 'N', 'SYSTEM');
INSERT INTO AP_LINE_TPL_STEP (TPL_ID, STEP_NO, LINE_TYP, APRV_USR_ID, APRV_USR_NM, FINAL_YN, REG_ID)
VALUES ((SELECT ID FROM AP_LINE_TPL WHERE COMP_CD='1000' AND DOC_TYP='PO' AND TPL_NM='발주 고액(1천만 이상)'), 2, 'APRV', 'admin', '시스템관리자', 'Y', 'SYSTEM');

COMMIT;
