-- =============================================================
-- 구매시스템 DDL - 35. 공통 첨부파일 + 알림(메일/SMS) 발송로그
--   CM_ATTACH : 문서유형/문서ID 기준 공통 첨부파일
--   CM_NOTICE : 메일/SMS 발송이력 (시뮬레이션 발송 + 추후 실연동)
-- =============================================================

CREATE TABLE CM_ATTACH (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD    VARCHAR2(18 CHAR),
  REF_TYP    VARCHAR2(18 CHAR) NOT NULL,   -- 문서유형(PR/PO/CT/IP/CL ...)
  REF_ID     NUMBER NOT NULL,              -- 문서 ID
  FILE_NM    VARCHAR2(400 CHAR) NOT NULL,  -- 원본 파일명
  STOR_NM    VARCHAR2(200 CHAR) NOT NULL,  -- 저장 파일명(UUID)
  FILE_PATH  VARCHAR2(1000 CHAR),          -- 저장 경로
  FILE_SIZE  NUMBER DEFAULT 0,
  CONTENT_TYP VARCHAR2(200 CHAR),
  REMARK     VARCHAR2(1000 CHAR),
  DEL_YN     CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE CM_ATTACH IS '공통 첨부파일';
COMMENT ON COLUMN CM_ATTACH.REF_TYP IS '참조 문서유형';
COMMENT ON COLUMN CM_ATTACH.REF_ID IS '참조 문서 ID';
CREATE INDEX IX_CM_ATTACH_1 ON CM_ATTACH (REF_TYP, REF_ID);

CREATE TABLE CM_NOTICE (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD    VARCHAR2(18 CHAR),
  NOTI_TYP   VARCHAR2(18 CHAR) NOT NULL,   -- EMAIL / SMS
  TO_ADDR    VARCHAR2(200 CHAR),           -- 수신 주소(이메일/전화)
  TO_USR_ID  VARCHAR2(18 CHAR),
  TITLE      VARCHAR2(400 CHAR),
  CONTENT    VARCHAR2(2000 CHAR),
  REF_TYP    VARCHAR2(18 CHAR),
  REF_ID     NUMBER,
  EVENT_CD   VARCHAR2(30 CHAR),            -- SUBMIT/APPROVED/REJECTED ...
  SEND_STS   VARCHAR2(18 CHAR) DEFAULT 'READY' NOT NULL,  -- READY/SENT/FAIL
  SENT_DT    TIMESTAMP(0) WITH LOCAL TIME ZONE,
  ERR_MSG    VARCHAR2(1000 CHAR),
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE CM_NOTICE IS '알림(메일/SMS) 발송이력';
COMMENT ON COLUMN CM_NOTICE.NOTI_TYP IS '알림유형(EMAIL/SMS)';
COMMENT ON COLUMN CM_NOTICE.SEND_STS IS '발송상태(READY/SENT/FAIL)';
CREATE INDEX IX_CM_NOTICE_1 ON CM_NOTICE (TO_USR_ID, SEND_STS);
CREATE INDEX IX_CM_NOTICE_2 ON CM_NOTICE (REF_TYP, REF_ID);
