-- =============================================================
-- 구매시스템 SEED - 36. 첨부파일 + 알림
-- =============================================================

INSERT INTO CM_CODE_GRP (GRP_CD, GRP_NM, REG_ID) VALUES ('NOTI_TYP', '알림유형', 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('NOTI_TYP', 'EMAIL', '이메일', 1, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('NOTI_TYP', 'SMS', 'SMS', 2, 'SYSTEM');

INSERT INTO CM_CODE_GRP (GRP_CD, GRP_NM, REG_ID) VALUES ('NOTI_STS', '알림 발송상태', 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('NOTI_STS', 'READY', '발송대기', 1, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('NOTI_STS', 'SENT', '발송완료', 2, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('NOTI_STS', 'FAIL', '발송실패', 3, 'SYSTEM');

-- 알림 이력 메뉴 (시스템관리 하위)
INSERT INTO CM_MENU (MENU_ID, MENU_NM, UP_MENU_ID, MENU_LVL, URL, ICON, SORT_NO, REG_ID) VALUES ('SYS_NOTICE', '알림 발송이력', 'SYS', 2, '/sys/notice', 'bell', 9.5, 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('ADMIN', 'SYS_NOTICE', 'MANAGEMENT', 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('USER', 'SYS_NOTICE', 'SAVE', 'SYSTEM');

COMMIT;
