-- =============================================================
-- 구매시스템 DDL - 39. 협력사 마스터 확장 + 신규등록 심사
--   VD_VENDOR 확장(상세정보/지급·계좌/담당정보/등록심사상태)
--   VD_CONTACT(담당자 복수), VD_LICENSE(면허/인증)
-- =============================================================

ALTER TABLE VD_VENDOR ADD (
  ZIP_CD        VARCHAR2(10 CHAR),
  ADDR_EN       VARCHAR2(300 CHAR),
  MOBILE        VARCHAR2(50 CHAR),
  HOMEPAGE      VARCHAR2(200 CHAR),
  IND_SECT_CD   VARCHAR2(18 CHAR),      -- 산업부문
  TRAD_FORM_CD  VARCHAR2(18 CHAR),      -- 거래형태
  VD_SIZE_CD    VARCHAR2(18 CHAR),      -- 회사규모
  LISTED_YN     CHAR(1 CHAR) DEFAULT 'N',  -- 상장여부
  FND_DATE      DATE,                   -- 설립일
  CURR_CD       VARCHAR2(3 CHAR) DEFAULT 'KRW',
  BANK_CD       VARCHAR2(18 CHAR),
  BANK_NM       VARCHAR2(100 CHAR),
  ACCT_NO       VARCHAR2(50 CHAR),
  ACCT_HOLDER   VARCHAR2(100 CHAR),
  TAX_BILL_TYP  VARCHAR2(18 CHAR),      -- 세금계산서 발행유형
  INV_VERI_YN   CHAR(1 CHAR) DEFAULT 'N',   -- 송장(인보이스) 검증여부
  PURC_CHRG_ID  VARCHAR2(18 CHAR),      -- 자사 구매담당자
  PURC_CHRG_NM  VARCHAR2(100 CHAR),
  TRAD_START_YMD DATE,                  -- 거래시작일
  REG_STS       VARCHAR2(18 CHAR) DEFAULT 'APPROVED' NOT NULL,  -- 등록심사상태
  REMARK        VARCHAR2(1000 CHAR)
);
COMMENT ON COLUMN VD_VENDOR.IND_SECT_CD IS '산업부문';
COMMENT ON COLUMN VD_VENDOR.TRAD_FORM_CD IS '거래형태';
COMMENT ON COLUMN VD_VENDOR.VD_SIZE_CD IS '회사규모';
COMMENT ON COLUMN VD_VENDOR.TAX_BILL_TYP IS '세금계산서 발행유형';
COMMENT ON COLUMN VD_VENDOR.REG_STS IS '등록심사상태(DRAFT/REQ/APPROVED/REJECTED)';

CREATE TABLE VD_CONTACT (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  VENDOR_ID  NUMBER NOT NULL,
  LINE_NO    NUMBER NOT NULL,
  CONTACT_NM VARCHAR2(100 CHAR) NOT NULL,
  POSITION   VARCHAR2(100 CHAR),
  DEPT       VARCHAR2(100 CHAR),
  TEL        VARCHAR2(50 CHAR),
  MOBILE     VARCHAR2(50 CHAR),
  EMAIL      VARCHAR2(100 CHAR),
  REP_YN     CHAR(1 CHAR) DEFAULT 'N',   -- 대표담당자
  REMARK     VARCHAR2(500 CHAR),
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_VD_CONTACT_1 UNIQUE (VENDOR_ID, LINE_NO),
  CONSTRAINT FK_VD_CONTACT_1 FOREIGN KEY (VENDOR_ID) REFERENCES VD_VENDOR (ID)
);
COMMENT ON TABLE VD_CONTACT IS '협력사 담당자';

CREATE TABLE VD_LICENSE (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  VENDOR_ID  NUMBER NOT NULL,
  LINE_NO    NUMBER NOT NULL,
  LIC_TYP    VARCHAR2(18 CHAR),          -- 면허/인증 유형
  LIC_NM     VARCHAR2(200 CHAR) NOT NULL,
  LIC_NO     VARCHAR2(100 CHAR),
  ISSUE_ORG  VARCHAR2(200 CHAR),         -- 발급기관
  ISSUE_YMD  DATE,
  EXPIRE_YMD DATE,
  REMARK     VARCHAR2(500 CHAR),
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_VD_LICENSE_1 UNIQUE (VENDOR_ID, LINE_NO),
  CONSTRAINT FK_VD_LICENSE_1 FOREIGN KEY (VENDOR_ID) REFERENCES VD_VENDOR (ID)
);
COMMENT ON TABLE VD_LICENSE IS '협력사 면허/인증';
CREATE INDEX IX_VD_LICENSE_1 ON VD_LICENSE (EXPIRE_YMD);
