-- =============================================================
-- 구매시스템 DDL - 41. 표준거래계약(거래기본계약) BC
--   BC_CONTRACT : 거래기본계약 헤더 (개정 차수 BC_REV, 만료관리, 자동갱신)
--   BC_CONTRACT_TERM : 계약 거래조건 조항
--   단가계약(CT)과 별개. 협력사와의 거래기본조건(결제/납품/유효기간) 계약.
-- =============================================================

CREATE TABLE BC_CONTRACT (
  ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD       VARCHAR2(18 CHAR) NOT NULL,
  BC_NO         VARCHAR2(30 CHAR) NOT NULL,    -- 계약번호(개정 차수 무관 동일)
  BC_REV        NUMBER DEFAULT 0 NOT NULL,     -- 개정 차수
  BC_TITLE      VARCHAR2(300 CHAR) NOT NULL,
  BC_TYP        VARCHAR2(18 CHAR) DEFAULT 'BASIC',  -- BASIC표준거래/AGREE거래약정/ETC기타
  VD_CD         VARCHAR2(18 CHAR),
  VD_NM         VARCHAR2(200 CHAR),
  PURC_GRP_CD   VARCHAR2(18 CHAR),
  CHRG_USR_ID   VARCHAR2(18 CHAR),
  CHRG_USR_NM   VARCHAR2(100 CHAR),
  VALID_SD      DATE,
  VALID_ED      DATE,
  PAY_COND      VARCHAR2(200 CHAR),            -- 결제조건
  DELY_COND     VARCHAR2(200 CHAR),            -- 납품조건
  CURR_CD       VARCHAR2(3 CHAR) DEFAULT 'KRW',
  AUTO_RENEW_YN CHAR(1 CHAR) DEFAULT 'N',      -- 자동갱신
  NOTICE_DAYS   NUMBER DEFAULT 30,             -- 만료 N일전 알림
  PREV_ID       NUMBER,                        -- 이전 차수 계약 ID(개정 연결)
  STS           VARCHAR2(18 CHAR) DEFAULT 'TMP' NOT NULL,  -- TMP/REQ/ACTIVE/EXPIRE/TERMINATE/CANCEL
  REMARK        VARCHAR2(2000 CHAR),
  USE_YN        CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN        CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID        VARCHAR2(18 CHAR),
  REG_DT        TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID        VARCHAR2(18 CHAR),
  MOD_DT        TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_BC_CONTRACT_1 UNIQUE (COMP_CD, BC_NO, BC_REV)
);
COMMENT ON TABLE BC_CONTRACT IS '표준거래계약(거래기본계약) 헤더';
COMMENT ON COLUMN BC_CONTRACT.BC_REV IS '개정 차수';
COMMENT ON COLUMN BC_CONTRACT.BC_TYP IS '계약유형(BASIC/AGREE/ETC)';
COMMENT ON COLUMN BC_CONTRACT.STS IS '상태(TMP/REQ/ACTIVE/EXPIRE/TERMINATE/CANCEL)';
COMMENT ON COLUMN BC_CONTRACT.PREV_ID IS '이전 차수 계약 ID';
CREATE INDEX IX_BC_CONTRACT_1 ON BC_CONTRACT (COMP_CD, VD_CD, STS);
CREATE INDEX IX_BC_CONTRACT_2 ON BC_CONTRACT (VALID_ED);

CREATE TABLE BC_CONTRACT_TERM (
  ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CONTRACT_ID  NUMBER NOT NULL,
  LINE_NO      NUMBER NOT NULL,
  TERM_NM      VARCHAR2(300 CHAR),            -- 조항명
  TERM_CONTENT VARCHAR2(2000 CHAR),           -- 조항 내용
  REMARK       VARCHAR2(500 CHAR),
  REG_ID       VARCHAR2(18 CHAR),
  REG_DT       TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_BC_CONTRACT_TERM_1 UNIQUE (CONTRACT_ID, LINE_NO),
  CONSTRAINT FK_BC_CONTRACT_TERM_1 FOREIGN KEY (CONTRACT_ID) REFERENCES BC_CONTRACT (ID)
);
COMMENT ON TABLE BC_CONTRACT_TERM IS '표준거래계약 거래조건 조항';
