-- =============================================================
-- 구매시스템 SEED - 42. 표준거래계약(BC)
-- =============================================================

-- 계약유형
INSERT INTO CM_CODE_GRP (GRP_CD, GRP_NM, REG_ID) VALUES ('BC_TYP', '거래계약 유형', 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('BC_TYP', 'BASIC', '표준거래계약', 1, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('BC_TYP', 'AGREE', '거래약정', 2, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('BC_TYP', 'ETC', '기타거래계약', 3, 'SYSTEM');

-- 계약상태
INSERT INTO CM_CODE_GRP (GRP_CD, GRP_NM, REG_ID) VALUES ('BC_STS', '거래계약 상태', 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('BC_STS', 'TMP', '작성중', 1, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('BC_STS', 'REQ', '상신(결재요청)', 2, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('BC_STS', 'ACTIVE', '계약중(발효)', 3, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('BC_STS', 'EXPIRE', '만료', 4, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('BC_STS', 'TERMINATE', '해지', 8, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('BC_STS', 'CANCEL', '취소', 9, 'SYSTEM');

-- 채번 (BC-YYYYMM-####)
INSERT INTO CM_DOC_NO (DOC_TYP, DOC_NM, PREFIX, DATE_FMT, SEQ_LEN, LAST_SEQ, REG_ID) VALUES ('BC', '표준거래계약', 'BC', 'YYYYMM', 4, 0, 'SYSTEM');

-- 상태전이 (상신/결재→발효/반려/회수/해지/취소)
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('BC', 'TMP', 'SUBMIT', 'REQ', '상신', 'FWD', 'N', 1, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('BC', 'REQ', 'APPROVE', 'ACTIVE', '계약발효', 'FWD', 'N', 1, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('BC', 'REQ', 'REJECT', 'TMP', '반려', 'BWD', 'Y', 2, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('BC', 'REQ', 'RECALL', 'TMP', '회수', 'BWD', 'N', 3, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('BC', 'TMP', 'CANCEL', 'CANCEL', '취소', 'END', 'Y', 9, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('BC', 'ACTIVE', 'TERMINATE', 'TERMINATE', '해지', 'END', 'Y', 8, 'SYSTEM');

-- 메뉴 (단가계약 앞, 표준거래계약)
INSERT INTO CM_MENU (MENU_ID, MENU_NM, UP_MENU_ID, MENU_LVL, URL, ICON, SORT_NO, REG_ID) VALUES ('PRO_BC', '표준거래계약', 'PRO', 2, '/pro/bc', 'file-text', 1.7, 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('ADMIN', 'PRO_BC', 'MANAGEMENT', 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('USER', 'PRO_BC', 'SAVE', 'SYSTEM');

COMMIT;
