-- =============================================================
-- 구매시스템 DDL - 43. 협력사 등급체계 정교화
--   협력사 세그먼트(SG) + 세그먼트별 등급행렬 + 평가팩터 2단계 가중치(카테고리)
-- =============================================================

-- 협력사 세그먼트(SG) 마스터
CREATE TABLE VD_SEGMENT (
  ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD       VARCHAR2(18 CHAR),
  SEG_CD        VARCHAR2(18 CHAR) NOT NULL,
  SEG_NM        VARCHAR2(100 CHAR) NOT NULL,
  DESCRIPTION   VARCHAR2(500 CHAR),
  DEFAULT_SHEET_CD VARCHAR2(18 CHAR),      -- 세그먼트 기본 평가시트
  SORT_NO       NUMBER DEFAULT 1,
  USE_YN        CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN        CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID        VARCHAR2(18 CHAR),
  REG_DT        TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID        VARCHAR2(18 CHAR),
  MOD_DT        TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_VD_SEGMENT_1 UNIQUE (SEG_CD)
);
COMMENT ON TABLE VD_SEGMENT IS '협력사 세그먼트(등급군)';
COMMENT ON COLUMN VD_SEGMENT.DEFAULT_SHEET_CD IS '세그먼트 기본 평가시트';

-- 협력사에 세그먼트 배정
ALTER TABLE VD_VENDOR ADD (SEG_CD VARCHAR2(18 CHAR), SEG_NM VARCHAR2(100 CHAR));
COMMENT ON COLUMN VD_VENDOR.SEG_CD IS '협력사 세그먼트';

-- 등급행렬을 세그먼트별로 (SEG_CD NULL=공통)
ALTER TABLE VD_EVAL_GRADE ADD (SEG_CD VARCHAR2(18 CHAR));
COMMENT ON COLUMN VD_EVAL_GRADE.SEG_CD IS '적용 세그먼트(NULL=공통)';
-- 등급코드는 세그먼트별로 중복 가능하므로 UK를 (GRADE_CD, SEG_CD)로 변경
ALTER TABLE VD_EVAL_GRADE DROP CONSTRAINT UX_VD_EVAL_GRADE_1;
ALTER TABLE VD_EVAL_GRADE ADD CONSTRAINT UX_VD_EVAL_GRADE_1 UNIQUE (GRADE_CD, SEG_CD);

-- 평가시트 2단계 가중치(카테고리/팩터그룹)
ALTER TABLE VD_EVAL_SHEET ADD (USE_CATE_YN CHAR(1 CHAR) DEFAULT 'N');
COMMENT ON COLUMN VD_EVAL_SHEET.USE_CATE_YN IS '카테고리(2단계 가중) 사용여부';

CREATE TABLE VD_EVAL_SHEET_CATE (
  ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SHEET_CD  VARCHAR2(18 CHAR) NOT NULL,
  CATE_SEQ  NUMBER NOT NULL,
  CATE_NM   VARCHAR2(200 CHAR) NOT NULL,
  WEIGHT    NUMBER(10,2) DEFAULT 0,        -- 카테고리 배점(합100)
  REG_ID    VARCHAR2(18 CHAR),
  REG_DT    TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_VD_EVAL_SHEET_CATE_1 UNIQUE (SHEET_CD, CATE_SEQ)
);
COMMENT ON TABLE VD_EVAL_SHEET_CATE IS '평가시트 카테고리(팩터그룹)';

-- 항목이 속한 카테고리
ALTER TABLE VD_EVAL_SHEET_ITEM ADD (CATE_SEQ NUMBER);
COMMENT ON COLUMN VD_EVAL_SHEET_ITEM.CATE_SEQ IS '소속 카테고리(2단계 시 항목 배점은 카테고리 내 합100)';

-- 평가 실행/결과에 세그먼트·카테고리 반영
ALTER TABLE VD_EVAL ADD (SEG_CD VARCHAR2(18 CHAR), SEG_NM VARCHAR2(100 CHAR));
ALTER TABLE VD_EVAL_RESULT ADD (CATE_SEQ NUMBER, CATE_NM VARCHAR2(200 CHAR));
