-- =============================================================
-- 구매시스템 SEED - 44. 협력사 등급체계 정교화
-- =============================================================

-- 협력사 세그먼트
INSERT INTO VD_SEGMENT (SEG_CD, SEG_NM, DESCRIPTION, DEFAULT_SHEET_CD, SORT_NO, REG_ID) VALUES ('STRAT', '전략 협력사', '핵심 전략품목 공급, 엄격 관리', 'STD2', 1, 'SYSTEM');
INSERT INTO VD_SEGMENT (SEG_CD, SEG_NM, DESCRIPTION, DEFAULT_SHEET_CD, SORT_NO, REG_ID) VALUES ('GENERAL', '일반 협력사', '일반 거래 협력사', 'STD', 2, 'SYSTEM');
INSERT INTO VD_SEGMENT (SEG_CD, SEG_NM, DESCRIPTION, DEFAULT_SHEET_CD, SORT_NO, REG_ID) VALUES ('ONETIME', '한시 협력사', '단기/일회성 거래', 'STD', 3, 'SYSTEM');

-- 세그먼트별 등급행렬 (전략협력사는 더 엄격)
INSERT INTO VD_EVAL_GRADE (GRADE_CD, GRADE_NM, MIN_SCORE, MAX_SCORE, ACTION_DESC, SORT_NO, SEG_CD, REG_ID) VALUES ('A', 'A(우수)', 95, 100, '전략적 파트너십 확대', 1, 'STRAT', 'SYSTEM');
INSERT INTO VD_EVAL_GRADE (GRADE_CD, GRADE_NM, MIN_SCORE, MAX_SCORE, ACTION_DESC, SORT_NO, SEG_CD, REG_ID) VALUES ('B', 'B(양호)', 88, 94.99, '정상거래', 2, 'STRAT', 'SYSTEM');
INSERT INTO VD_EVAL_GRADE (GRADE_CD, GRADE_NM, MIN_SCORE, MAX_SCORE, ACTION_DESC, SORT_NO, SEG_CD, REG_ID) VALUES ('C', 'C(보통)', 80, 87.99, '집중관찰/개선요청', 3, 'STRAT', 'SYSTEM');
INSERT INTO VD_EVAL_GRADE (GRADE_CD, GRADE_NM, MIN_SCORE, MAX_SCORE, ACTION_DESC, SORT_NO, SEG_CD, REG_ID) VALUES ('D', 'D(미흡)', 0, 79.99, '세그먼트 강등 검토', 4, 'STRAT', 'SYSTEM');

-- 2단계 가중 평가시트 STD2 (카테고리: 품질역량50 / 운영역량30 / 거래신뢰20)
INSERT INTO VD_EVAL_SHEET (SHEET_CD, SHEET_NM, EVAL_TYP, DESCRIPTION, USE_CATE_YN, REG_ID) VALUES ('STD2', '2단계 가중 종합평가', 'REGULAR', '카테고리 가중 + 항목 가중 2단계', 'Y', 'SYSTEM');
INSERT INTO VD_EVAL_SHEET_CATE (SHEET_CD, CATE_SEQ, CATE_NM, WEIGHT, REG_ID) VALUES ('STD2', 1, '품질역량', 50, 'SYSTEM');
INSERT INTO VD_EVAL_SHEET_CATE (SHEET_CD, CATE_SEQ, CATE_NM, WEIGHT, REG_ID) VALUES ('STD2', 2, '운영역량', 30, 'SYSTEM');
INSERT INTO VD_EVAL_SHEET_CATE (SHEET_CD, CATE_SEQ, CATE_NM, WEIGHT, REG_ID) VALUES ('STD2', 3, '거래신뢰', 20, 'SYSTEM');
-- 항목(카테고리 내 합100)
INSERT INTO VD_EVAL_SHEET_ITEM (SHEET_CD, ITEM_SEQ, EVAL_ITEM_NM, EVAL_CLS, WEIGHT, CATE_SEQ, REG_ID) VALUES ('STD2', 1, '품질수준', 'QUANT', 60, 1, 'SYSTEM');
INSERT INTO VD_EVAL_SHEET_ITEM (SHEET_CD, ITEM_SEQ, EVAL_ITEM_NM, EVAL_CLS, WEIGHT, CATE_SEQ, REG_ID) VALUES ('STD2', 2, '위생/안전 관리', 'QUANT', 40, 1, 'SYSTEM');
INSERT INTO VD_EVAL_SHEET_ITEM (SHEET_CD, ITEM_SEQ, EVAL_ITEM_NM, EVAL_CLS, WEIGHT, CATE_SEQ, REG_ID) VALUES ('STD2', 3, '납기준수', 'QUANT', 60, 2, 'SYSTEM');
INSERT INTO VD_EVAL_SHEET_ITEM (SHEET_CD, ITEM_SEQ, EVAL_ITEM_NM, EVAL_CLS, WEIGHT, CATE_SEQ, REG_ID) VALUES ('STD2', 4, '생산/공급 능력', 'QUANT', 40, 2, 'SYSTEM');
INSERT INTO VD_EVAL_SHEET_ITEM (SHEET_CD, ITEM_SEQ, EVAL_ITEM_NM, EVAL_CLS, WEIGHT, CATE_SEQ, REG_ID) VALUES ('STD2', 5, '가격경쟁력', 'QUANT', 50, 3, 'SYSTEM');
INSERT INTO VD_EVAL_SHEET_ITEM (SHEET_CD, ITEM_SEQ, EVAL_ITEM_NM, EVAL_CLS, WEIGHT, CATE_SEQ, REG_ID) VALUES ('STD2', 6, '협조도/소통', 'QUAL', 50, 3, 'SYSTEM');

-- 메뉴: 협력사 세그먼트 (SRM 하위, 평가시트 앞)
INSERT INTO CM_MENU (MENU_ID, MENU_NM, UP_MENU_ID, MENU_LVL, URL, ICON, SORT_NO, REG_ID) VALUES ('SRM_SEG', '협력사 세그먼트', 'SRM', 2, '/srm/segment', 'layers', 0.5, 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('ADMIN', 'SRM_SEG', 'MANAGEMENT', 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('USER', 'SRM_SEG', 'SAVE', 'SYSTEM');

COMMIT;
