-- =============================================================
-- 구매시스템 DDL - 47. 매입조정(PA)
--   입고확정 후 가격/수량/반품에 따른 매입금액 조정. 결재 후 정산(CL)에 반영.
-- =============================================================

CREATE TABLE PA_ADJUST (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD     VARCHAR2(18 CHAR) NOT NULL,
  ADJ_NO      VARCHAR2(30 CHAR) NOT NULL,
  ADJ_TYP     VARCHAR2(18 CHAR) DEFAULT 'PRICE',  -- PRICE가격/QTY수량/RETURN반품/ETC기타
  VD_CD       VARCHAR2(18 CHAR),
  VD_NM       VARCHAR2(200 CHAR),
  GR_ID       NUMBER,                              -- 대상 입고(선택)
  GR_NO       VARCHAR2(30 CHAR),
  ADJ_YM      VARCHAR2(6 CHAR),                    -- 반영 정산월(YYYYMM)
  SUPL_ADJ_AMT NUMBER(20,5) DEFAULT 0,             -- 공급가 조정(±)
  VAT_ADJ_AMT  NUMBER(20,5) DEFAULT 0,
  TOT_ADJ_AMT  NUMBER(20,5) DEFAULT 0,
  REASON      VARCHAR2(1000 CHAR),
  STS         VARCHAR2(18 CHAR) DEFAULT 'TMP' NOT NULL,  -- TMP/REQ/CFM/CANCEL
  REMARK      VARCHAR2(1000 CHAR),
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_PA_ADJUST_1 UNIQUE (COMP_CD, ADJ_NO)
);
COMMENT ON TABLE PA_ADJUST IS '매입조정';
COMMENT ON COLUMN PA_ADJUST.ADJ_TYP IS '조정유형(PRICE/QTY/RETURN/ETC)';
COMMENT ON COLUMN PA_ADJUST.SUPL_ADJ_AMT IS '공급가 조정금액(±)';
COMMENT ON COLUMN PA_ADJUST.ADJ_YM IS '반영 정산월(YYYYMM)';
COMMENT ON COLUMN PA_ADJUST.STS IS '상태(TMP/REQ/CFM확정/CANCEL)';
CREATE INDEX IX_PA_ADJUST_1 ON PA_ADJUST (COMP_CD, VD_CD, ADJ_YM, STS);
