-- =============================================================
-- 구매시스템 DDL - 49. 선급금/반제(AV)
--   협력사 선지급금. 결재확정 후 잔액관리, 반제(상계)로 차감.
-- =============================================================

CREATE TABLE AV_ADVANCE (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD    VARCHAR2(18 CHAR) NOT NULL,
  ADV_NO     VARCHAR2(30 CHAR) NOT NULL,
  VD_CD      VARCHAR2(18 CHAR),
  VD_NM      VARCHAR2(200 CHAR),
  ADV_AMT    NUMBER(20,5) DEFAULT 0,        -- 선급금액
  PAY_YMD    DATE,                          -- 지급예정일
  PURPOSE    VARCHAR2(500 CHAR),            -- 용도
  BALANCE    NUMBER(20,5) DEFAULT 0,        -- 미반제 잔액
  STS        VARCHAR2(18 CHAR) DEFAULT 'TMP' NOT NULL,  -- TMP/REQ/CFM/CLOSED/CANCEL
  REMARK     VARCHAR2(1000 CHAR),
  USE_YN     CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN     CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID     VARCHAR2(18 CHAR),
  MOD_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_AV_ADVANCE_1 UNIQUE (COMP_CD, ADV_NO)
);
COMMENT ON TABLE AV_ADVANCE IS '선급금';
COMMENT ON COLUMN AV_ADVANCE.BALANCE IS '미반제 잔액';
COMMENT ON COLUMN AV_ADVANCE.STS IS '상태(TMP/REQ/CFM지급확정/CLOSED반제완료/CANCEL)';
CREATE INDEX IX_AV_ADVANCE_1 ON AV_ADVANCE (COMP_CD, VD_CD, STS);

CREATE TABLE AV_REPAY (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ADVANCE_ID NUMBER NOT NULL,
  LINE_NO    NUMBER NOT NULL,
  REPAY_AMT  NUMBER(20,5) DEFAULT 0,
  REPAY_YMD  DATE,
  CLOSE_NO   VARCHAR2(30 CHAR),             -- 연계 정산마감(선택)
  REMARK     VARCHAR2(500 CHAR),
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_AV_REPAY_1 UNIQUE (ADVANCE_ID, LINE_NO),
  CONSTRAINT FK_AV_REPAY_1 FOREIGN KEY (ADVANCE_ID) REFERENCES AV_ADVANCE (ID)
);
COMMENT ON TABLE AV_REPAY IS '선급금 반제(상계) 내역';
