-- =============================================================
-- 구매시스템 DDL - 51. 품질 CAPA (부적합/개선대책)
--   QC_NONCONF  : 부적합 (입고검사 불합격 등)
--   QC_ACTION   : 개선조치 (시정조치 CORRECTIVE / 예방조치 PREVENTIVE)
-- =============================================================

CREATE TABLE QC_NONCONF (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD    VARCHAR2(18 CHAR) NOT NULL,
  NC_NO      VARCHAR2(30 CHAR) NOT NULL,
  VD_CD      VARCHAR2(18 CHAR),
  VD_NM      VARCHAR2(200 CHAR),
  SRC_TYP    VARCHAR2(18 CHAR),          -- QL입고검사/GR입고/SELF자체
  SRC_ID     NUMBER,
  REF_NO     VARCHAR2(30 CHAR),          -- 검사번호/입고번호 등
  ITEM_CD    VARCHAR2(18 CHAR),
  ITEM_NM    VARCHAR2(300 CHAR),
  NC_TYP     VARCHAR2(18 CHAR) DEFAULT 'QUALITY',  -- QUALITY/HYGIENE/PACK/SPEC/FOREIGN/ETC
  SEVERITY   VARCHAR2(18 CHAR) DEFAULT 'MAJOR',    -- MINOR/MAJOR/CRITICAL
  DETECT_YMD DATE,
  NC_QTY     NUMBER(20,5) DEFAULT 0,
  NC_DESC    VARCHAR2(2000 CHAR),        -- 부적합 내용
  STS        VARCHAR2(18 CHAR) DEFAULT 'OPEN' NOT NULL,  -- OPEN/REQ/ACTION/CLOSED/CANCEL
  REMARK     VARCHAR2(1000 CHAR),
  USE_YN     CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN     CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID     VARCHAR2(18 CHAR),
  MOD_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_QC_NONCONF_1 UNIQUE (COMP_CD, NC_NO)
);
COMMENT ON TABLE QC_NONCONF IS '품질 부적합';
COMMENT ON COLUMN QC_NONCONF.NC_TYP IS '부적합유형(QUALITY/HYGIENE/PACK/SPEC/FOREIGN/ETC)';
COMMENT ON COLUMN QC_NONCONF.SEVERITY IS '심각도(MINOR/MAJOR/CRITICAL)';
COMMENT ON COLUMN QC_NONCONF.STS IS '상태(OPEN/REQ개선요청/ACTION조치중/CLOSED종료/CANCEL)';
CREATE INDEX IX_QC_NONCONF_1 ON QC_NONCONF (COMP_CD, VD_CD, STS);

CREATE TABLE QC_ACTION (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NC_ID       NUMBER NOT NULL,
  LINE_NO     NUMBER NOT NULL,
  ACTION_TYP  VARCHAR2(18 CHAR) DEFAULT 'CORRECT',  -- CORRECT시정/PREVENT예방
  ROOT_CAUSE  VARCHAR2(1000 CHAR),       -- 원인분석
  ACTION_DESC VARCHAR2(1000 CHAR),       -- 조치내용
  RESP_NM     VARCHAR2(100 CHAR),        -- 담당
  DUE_YMD     DATE,                      -- 완료기한
  COMPLETE_YMD DATE,                     -- 완료일
  RESULT_STS  VARCHAR2(18 CHAR) DEFAULT 'PLAN',     -- PLAN/DOING/DONE/VERIFIED
  REMARK      VARCHAR2(500 CHAR),
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_QC_ACTION_1 UNIQUE (NC_ID, LINE_NO),
  CONSTRAINT FK_QC_ACTION_1 FOREIGN KEY (NC_ID) REFERENCES QC_NONCONF (ID)
);
COMMENT ON TABLE QC_ACTION IS '품질 개선조치(시정/예방)';
COMMENT ON COLUMN QC_ACTION.ACTION_TYP IS '조치유형(CORRECT시정/PREVENT예방)';
COMMENT ON COLUMN QC_ACTION.RESULT_STS IS '조치상태(PLAN/DOING/DONE/VERIFIED)';
