-- =============================================================
-- 구매시스템 DDL - 55. 협력사 클레임(CLM)
-- =============================================================

CREATE TABLE CM_CLAIM (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD     VARCHAR2(18 CHAR) NOT NULL,
  CLM_NO      VARCHAR2(30 CHAR) NOT NULL,
  VD_CD       VARCHAR2(18 CHAR),
  VD_NM       VARCHAR2(200 CHAR),
  CLM_TYP     VARCHAR2(18 CHAR) DEFAULT 'QUALITY',  -- QUALITY/DELIVERY/QTY/SERVICE/ETC
  SRC_TYP     VARCHAR2(18 CHAR),                     -- GR/QC/SELF
  REF_NO      VARCHAR2(30 CHAR),
  ITEM_CD     VARCHAR2(18 CHAR),
  ITEM_NM     VARCHAR2(300 CHAR),
  CLM_YMD     DATE,
  CLM_AMT     NUMBER(20,5) DEFAULT 0,               -- 클레임 비용/손해액
  CLM_DESC    VARCHAR2(2000 CHAR),
  DUE_YMD     DATE,                                 -- 처리기한
  RESOLVE_DESC VARCHAR2(2000 CHAR),                 -- 처리/조치 내용
  STS         VARCHAR2(18 CHAR) DEFAULT 'OPEN' NOT NULL,  -- OPEN/PROC/RESOLVED/CLOSED/CANCEL
  REMARK      VARCHAR2(1000 CHAR),
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_CM_CLAIM_1 UNIQUE (COMP_CD, CLM_NO)
);
COMMENT ON TABLE CM_CLAIM IS '협력사 클레임';
COMMENT ON COLUMN CM_CLAIM.CLM_TYP IS '클레임유형(QUALITY/DELIVERY/QTY/SERVICE/ETC)';
COMMENT ON COLUMN CM_CLAIM.STS IS '상태(OPEN/PROC처리중/RESOLVED해결/CLOSED종결/CANCEL)';
CREATE INDEX IX_CM_CLAIM_1 ON CM_CLAIM (COMP_CD, VD_CD, STS);
