-- =============================================================
-- 구매시스템 DDL - 56. 구매계획(PP)
--   연간 품목별 구매계획 + 입고실적 대비 달성률
-- =============================================================

CREATE TABLE PP_PLAN (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD     VARCHAR2(18 CHAR) NOT NULL,
  PLAN_NO     VARCHAR2(30 CHAR) NOT NULL,
  PLAN_YEAR   VARCHAR2(4 CHAR) NOT NULL,
  PLAN_NM     VARCHAR2(300 CHAR) NOT NULL,
  PURC_GRP_CD VARCHAR2(18 CHAR),
  TOT_PLAN_AMT NUMBER(20,5) DEFAULT 0,
  STS         VARCHAR2(18 CHAR) DEFAULT 'DRAFT' NOT NULL,  -- DRAFT/CONFIRMED/CLOSED
  REMARK      VARCHAR2(1000 CHAR),
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_PP_PLAN_1 UNIQUE (COMP_CD, PLAN_NO)
);
COMMENT ON TABLE PP_PLAN IS '구매계획 헤더';
COMMENT ON COLUMN PP_PLAN.STS IS '상태(DRAFT/CONFIRMED확정/CLOSED마감)';

CREATE TABLE PP_PLAN_ITEM (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PLAN_ID    NUMBER NOT NULL,
  LINE_NO    NUMBER NOT NULL,
  ITEM_CD    VARCHAR2(18 CHAR),
  ITEM_NM    VARCHAR2(300 CHAR),
  UNIT_CD    VARCHAR2(18 CHAR),
  PLAN_QTY   NUMBER(20,5) DEFAULT 0,
  PLAN_AMT   NUMBER(20,5) DEFAULT 0,
  REMARK     VARCHAR2(500 CHAR),
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_PP_PLAN_ITEM_1 UNIQUE (PLAN_ID, LINE_NO),
  CONSTRAINT FK_PP_PLAN_ITEM_1 FOREIGN KEY (PLAN_ID) REFERENCES PP_PLAN (ID)
);
COMMENT ON TABLE PP_PLAN_ITEM IS '구매계획 품목';
