-- =============================================================
-- 구매시스템 SEED - 57. 구매계획(PP)
-- =============================================================

INSERT INTO CM_CODE_GRP (GRP_CD, GRP_NM, REG_ID) VALUES ('PP_STS', '구매계획 상태', 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('PP_STS', 'DRAFT', '작성중', 1, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('PP_STS', 'CONFIRMED', '확정', 2, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('PP_STS', 'CLOSED', '마감', 3, 'SYSTEM');

INSERT INTO CM_DOC_NO (DOC_TYP, DOC_NM, PREFIX, DATE_FMT, SEQ_LEN, LAST_SEQ, REG_ID) VALUES ('PP', '구매계획', 'PP', 'YYYY', 4, 0, 'SYSTEM');

INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('PP', 'DRAFT', 'CONFIRM', 'CONFIRMED', '확정', 'FWD', 'N', 1, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('PP', 'CONFIRMED', 'REOPEN', 'DRAFT', '확정취소', 'BWD', 'Y', 2, 'SYSTEM');
INSERT INTO CM_STATUS_FLOW (DOC_TYP, FROM_STS, ACTION, TO_STS, ACTION_NM, DIRECTION, RSN_REQ_YN, SORT_NO, REG_ID)
VALUES ('PP', 'CONFIRMED', 'CLOSE', 'CLOSED', '마감', 'END', 'N', 3, 'SYSTEM');

INSERT INTO CM_MENU (MENU_ID, MENU_NM, UP_MENU_ID, MENU_LVL, URL, ICON, SORT_NO, REG_ID) VALUES ('PRO_PP', '구매계획', 'PRO', 2, '/pro/pp', 'clipboard', 0.5, 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('ADMIN', 'PRO_PP', 'MANAGEMENT', 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('USER', 'PRO_PP', 'SAVE', 'SYSTEM');

COMMIT;
