-- =============================================================
-- 구매시스템 DDL - 58. 품목 동적속성 + 등록요청
--   IT_CATE_ATTR     : 분류별 속성 정의
--   IT_ITEM_ATTR     : 품목 속성값
--   IT_ITEM_REQ      : 품목 등록요청 (승인 시 품목 생성)
--   IT_ITEM_REQ_ATTR : 등록요청 속성값
-- =============================================================

CREATE TABLE IT_CATE_ATTR (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CATE_CD    VARCHAR2(18 CHAR) NOT NULL,
  ATTR_SEQ   NUMBER NOT NULL,
  ATTR_NM    VARCHAR2(200 CHAR) NOT NULL,
  ATTR_TYP   VARCHAR2(18 CHAR) DEFAULT 'TEXT',   -- TEXT/NUM/DATE/SELECT
  OPTION_VALS VARCHAR2(1000 CHAR),               -- SELECT 옵션(콤마구분)
  REQUIRED_YN CHAR(1 CHAR) DEFAULT 'N',
  SORT_NO    NUMBER DEFAULT 1,
  USE_YN     CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN     CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_IT_CATE_ATTR_1 UNIQUE (CATE_CD, ATTR_SEQ)
);
COMMENT ON TABLE IT_CATE_ATTR IS '분류별 속성 정의';
COMMENT ON COLUMN IT_CATE_ATTR.ATTR_TYP IS '속성유형(TEXT/NUM/DATE/SELECT)';

CREATE TABLE IT_ITEM_ATTR (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ITEM_ID    NUMBER NOT NULL,
  ATTR_NM    VARCHAR2(200 CHAR) NOT NULL,
  ATTR_VAL   VARCHAR2(1000 CHAR),
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_IT_ITEM_ATTR_1 UNIQUE (ITEM_ID, ATTR_NM)
);
COMMENT ON TABLE IT_ITEM_ATTR IS '품목 속성값';

CREATE TABLE IT_ITEM_REQ (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD     VARCHAR2(18 CHAR) NOT NULL,
  REQ_NO      VARCHAR2(30 CHAR) NOT NULL,
  ITEM_NM     VARCHAR2(300 CHAR) NOT NULL,
  ITEM_NM_EN  VARCHAR2(300 CHAR),
  CATE_CD     VARCHAR2(18 CHAR),
  CATE_NM     VARCHAR2(200 CHAR),
  SPEC        VARCHAR2(500 CHAR),
  UNIT_CD     VARCHAR2(18 CHAR),
  ITEM_TYP    VARCHAR2(18 CHAR),
  TAX_TYP     VARCHAR2(18 CHAR) DEFAULT 'TAX',
  REQ_DESC    VARCHAR2(1000 CHAR),
  STS         VARCHAR2(18 CHAR) DEFAULT 'REQ' NOT NULL,  -- REQ/APPROVED/REJECTED/CANCEL
  CREATED_ITEM_CD VARCHAR2(18 CHAR),                     -- 승인 시 생성된 품목코드
  REMARK      VARCHAR2(1000 CHAR),
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_IT_ITEM_REQ_1 UNIQUE (COMP_CD, REQ_NO)
);
COMMENT ON TABLE IT_ITEM_REQ IS '품목 등록요청';
COMMENT ON COLUMN IT_ITEM_REQ.STS IS '상태(REQ/APPROVED/REJECTED/CANCEL)';

CREATE TABLE IT_ITEM_REQ_ATTR (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  REQ_ID     NUMBER NOT NULL,
  ATTR_NM    VARCHAR2(200 CHAR) NOT NULL,
  ATTR_VAL   VARCHAR2(1000 CHAR),
  CONSTRAINT UX_IT_ITEM_REQ_ATTR_1 UNIQUE (REQ_ID, ATTR_NM),
  CONSTRAINT FK_IT_ITEM_REQ_ATTR_1 FOREIGN KEY (REQ_ID) REFERENCES IT_ITEM_REQ (ID)
);
COMMENT ON TABLE IT_ITEM_REQ_ATTR IS '품목 등록요청 속성값';
