-- =============================================================
-- 구매시스템 DDL - 60. 인터페이스 연계 프레임 (SAP/EAI/국세청)
--   IF_INTERFACE : 대외 인터페이스 송수신 이력 (시뮬레이션 발송)
-- =============================================================

CREATE TABLE IF_INTERFACE (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD    VARCHAR2(18 CHAR),
  IF_NO      VARCHAR2(30 CHAR) NOT NULL,
  IF_TYP     VARCHAR2(30 CHAR) NOT NULL,   -- VENDOR_MASTER/ITEM_MASTER/PO_SEND/GR_SEND/CL_SEND/TAXBILL/SLIP
  IF_NM      VARCHAR2(200 CHAR),
  DIRECTION  VARCHAR2(10 CHAR) DEFAULT 'SEND',  -- SEND/RECV
  SYS_CD     VARCHAR2(18 CHAR),            -- SAP/INDIGO/NTS
  REF_TYP    VARCHAR2(18 CHAR),
  REF_ID     NUMBER,
  REF_NO     VARCHAR2(30 CHAR),
  PAYLOAD    VARCHAR2(2000 CHAR),
  IF_STATUS  VARCHAR2(18 CHAR) DEFAULT 'READY' NOT NULL,  -- READY/SUCCESS/FAIL
  SENT_DT    TIMESTAMP(0) WITH LOCAL TIME ZONE,
  RESULT_MSG VARCHAR2(1000 CHAR),
  RETRY_CNT  NUMBER DEFAULT 0,
  REG_ID     VARCHAR2(18 CHAR),
  REG_DT     TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_IF_INTERFACE_1 UNIQUE (IF_NO)
);
COMMENT ON TABLE IF_INTERFACE IS '대외 인터페이스 송수신 이력';
COMMENT ON COLUMN IF_INTERFACE.IF_TYP IS '인터페이스 유형';
COMMENT ON COLUMN IF_INTERFACE.SYS_CD IS '연계 시스템(SAP/INDIGO/NTS)';
COMMENT ON COLUMN IF_INTERFACE.IF_STATUS IS '연계상태(READY/SUCCESS/FAIL)';
CREATE INDEX IX_IF_INTERFACE_1 ON IF_INTERFACE (IF_TYP, IF_STATUS);
CREATE INDEX IX_IF_INTERFACE_2 ON IF_INTERFACE (REF_TYP, REF_ID);
