-- =============================================================
-- 구매시스템 DDL - 62. 전자세금계산서 + 회계전표 (SAP/국세청 연계)
-- =============================================================

CREATE TABLE TX_TAXBILL (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD     VARCHAR2(18 CHAR) NOT NULL,
  BILL_NO     VARCHAR2(30 CHAR) NOT NULL,
  CLOSE_ID    NUMBER,
  CLOSE_NO    VARCHAR2(30 CHAR),
  VD_CD       VARCHAR2(18 CHAR),
  VD_NM       VARCHAR2(200 CHAR),
  BILL_YMD    DATE,
  BILL_TYP    VARCHAR2(18 CHAR) DEFAULT 'TAX',   -- TAX과세/FREE면세
  SUPPLY_AMT  NUMBER(20,5) DEFAULT 0,
  VAT_AMT     NUMBER(20,5) DEFAULT 0,
  TOT_AMT     NUMBER(20,5) DEFAULT 0,
  BILL_STS    VARCHAR2(18 CHAR) DEFAULT 'DRAFT' NOT NULL,  -- DRAFT/ISSUED/SENT/CANCEL
  NTS_STATUS  VARCHAR2(18 CHAR),                 -- 국세청 전송상태(시뮬)
  REMARK      VARCHAR2(1000 CHAR),
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_TX_TAXBILL_1 UNIQUE (COMP_CD, BILL_NO)
);
COMMENT ON TABLE TX_TAXBILL IS '전자세금계산서';
COMMENT ON COLUMN TX_TAXBILL.BILL_STS IS '상태(DRAFT/ISSUED발행/SENT전송/CANCEL)';

CREATE TABLE AC_SLIP (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD     VARCHAR2(18 CHAR) NOT NULL,
  SLIP_NO     VARCHAR2(30 CHAR) NOT NULL,
  SLIP_TYP    VARCHAR2(18 CHAR) DEFAULT 'PURCHASE',  -- PURCHASE매입/ADVANCE선급/ADJUST조정
  SRC_TYP     VARCHAR2(18 CHAR),                     -- CL/PA/AV
  SRC_ID      NUMBER,
  SRC_NO      VARCHAR2(30 CHAR),
  VD_CD       VARCHAR2(18 CHAR),
  VD_NM       VARCHAR2(200 CHAR),
  POSTING_YMD DATE,
  DR_ACCT     VARCHAR2(100 CHAR),         -- 차변계정
  CR_ACCT     VARCHAR2(100 CHAR),         -- 대변계정
  AMT         NUMBER(20,5) DEFAULT 0,
  SLIP_STS    VARCHAR2(18 CHAR) DEFAULT 'DRAFT' NOT NULL,  -- DRAFT/POSTED/SENT/CANCEL
  REMARK      VARCHAR2(1000 CHAR),
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_AC_SLIP_1 UNIQUE (COMP_CD, SLIP_NO)
);
COMMENT ON TABLE AC_SLIP IS '회계전표';
COMMENT ON COLUMN AC_SLIP.SLIP_STS IS '상태(DRAFT/POSTED전기/SENT전송/CANCEL)';
