-- =============================================================
-- 구매시스템 DDL - 70. (C7c) 지급(Payment) 단계
--   정산 기반 지급예정/실행/방법/어음/계좌 — "언제 얼마를 어떻게 지급했나"
-- =============================================================

INSERT INTO CM_CODE_GRP (GRP_CD, GRP_NM, REG_ID) VALUES ('PY_STS', '지급상태', 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('PY_STS', 'PLAN',   '지급예정', 1, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('PY_STS', 'PAID',   '지급완료', 2, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('PY_STS', 'CANCEL', '취소',     9, 'SYSTEM');

INSERT INTO CM_DOC_NO (DOC_TYP, DOC_NM, PREFIX, DATE_FMT, SEQ_LEN, LAST_SEQ, REG_ID) VALUES ('PY', '지급', 'PY', 'YYYYMM', 4, 0, 'SYSTEM');

CREATE TABLE PY_PAYMENT (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD     VARCHAR2(18 CHAR) NOT NULL,
  PAY_NO      VARCHAR2(30 CHAR) NOT NULL,
  SRC_TYP     VARCHAR2(18 CHAR),         -- CL
  SRC_ID      NUMBER,
  SRC_NO      VARCHAR2(30 CHAR),
  VD_CD       VARCHAR2(18 CHAR),
  VD_NM       VARCHAR2(200 CHAR),
  PAY_DUE_YMD DATE,                      -- 지급예정일(정산 결제조건 기반)
  PAY_AMT     NUMBER(20,5) DEFAULT 0,    -- 지급액(정산 최종액)
  PAY_METHOD_CD VARCHAR2(18 CHAR),       -- 지급방법(이체/어음/현금/상계)
  BANK_CD     VARCHAR2(18 CHAR),
  BANK_NM     VARCHAR2(100 CHAR),
  ACCT_NO     VARCHAR2(50 CHAR),
  ACCT_HOLDER VARCHAR2(100 CHAR),
  NOTE_NO     VARCHAR2(50 CHAR),         -- 어음번호
  NOTE_DUE_YMD DATE,                     -- 어음만기일
  PAY_YMD     DATE,                      -- 실지급일
  PAY_STS     VARCHAR2(18 CHAR) DEFAULT 'PLAN' NOT NULL,
  REMARK      VARCHAR2(1000 CHAR),
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_PY_PAYMENT_1 UNIQUE (COMP_CD, PAY_NO)
);
COMMENT ON TABLE PY_PAYMENT IS '지급';
COMMENT ON COLUMN PY_PAYMENT.PAY_STS IS '지급상태(PLAN예정/PAID완료/CANCEL)';

INSERT INTO CM_MENU (MENU_ID, MENU_NM, UP_MENU_ID, MENU_LVL, URL, ICON, SORT_NO, REG_ID) VALUES ('PRO_PY', '지급관리', 'PRO', 2, '/pro/payment', 'card', 20, 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('ADMIN', 'PRO_PY', 'MANAGEMENT', 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('USER', 'PRO_PY', 'SAVE', 'SYSTEM');

COMMIT;
