-- =============================================================
-- 구매시스템 DDL - 72. (3a) 예산통제 + 여신한도
--   BG_BUDGET 예산마스터 + PR 예산연계, 협력사 여신한도
-- =============================================================

-- ---------- 예산 마스터 ----------
CREATE TABLE BG_BUDGET (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD     VARCHAR2(18 CHAR) NOT NULL,
  BUDGET_CD   VARCHAR2(18 CHAR) NOT NULL,
  BUDGET_NM   VARCHAR2(200 CHAR) NOT NULL,
  FISCAL_YEAR VARCHAR2(4 CHAR),
  DEPT_CD     VARCHAR2(18 CHAR),
  ACCT_CD     VARCHAR2(18 CHAR),
  BUDGET_AMT  NUMBER(20,5) DEFAULT 0,   -- 예산액
  USE_YN      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  DEL_YN      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID      VARCHAR2(18 CHAR),
  REG_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID      VARCHAR2(18 CHAR),
  MOD_DT      TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT UX_BG_BUDGET_1 UNIQUE (COMP_CD, BUDGET_CD)
);
COMMENT ON TABLE BG_BUDGET IS '예산 마스터';

-- ---------- 구매요청: 예산 연계 ----------
ALTER TABLE PR_REQUEST ADD (BUDGET_CD VARCHAR2(18 CHAR));
COMMENT ON COLUMN PR_REQUEST.BUDGET_CD IS '예산코드(예산통제)';

-- ---------- 협력사: 여신한도 ----------
ALTER TABLE VD_VENDOR ADD (CREDIT_LIMIT NUMBER(20,5) DEFAULT 0);
COMMENT ON COLUMN VD_VENDOR.CREDIT_LIMIT IS '여신한도(0=무제한)';

-- ---------- 시드 ----------
INSERT INTO BG_BUDGET (COMP_CD, BUDGET_CD, BUDGET_NM, FISCAL_YEAR, ACCT_CD, BUDGET_AMT, REG_ID)
  VALUES ('1000', 'BG2026-RAW', '2026 원재료 구매예산', '2026', '14900', 500000000, 'SYSTEM');
INSERT INTO BG_BUDGET (COMP_CD, BUDGET_CD, BUDGET_NM, FISCAL_YEAR, ACCT_CD, BUDGET_AMT, REG_ID)
  VALUES ('1000', 'BG2026-MRO', '2026 소모품/MRO 예산', '2026', '53500', 50000000, 'SYSTEM');

UPDATE VD_VENDOR SET CREDIT_LIMIT = 100000000 WHERE VD_CD = 'VD-00001';

INSERT INTO CM_MENU (MENU_ID, MENU_NM, UP_MENU_ID, MENU_LVL, URL, ICON, SORT_NO, REG_ID) VALUES ('BASE_BG', '예산관리', 'BASE', 2, '/base/budget', 'wallet', 30, 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('ADMIN', 'BASE_BG', 'MANAGEMENT', 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('USER', 'BASE_BG', 'SAVE', 'SYSTEM');

COMMIT;
