-- =============================================================
-- 구매시스템 DDL - 77. MRP / 자동발주
--   품목 발주정책 + MRP 실행(현재고+입고예정 vs 발주점) + 발주제안 → PR 자동생성
-- =============================================================

-- ---------- 품목 발주정책 ----------
ALTER TABLE IT_ITEM ADD (
  SAFETY_STOCK  NUMBER(20,5) DEFAULT 0,   -- 안전재고
  REORDER_POINT NUMBER(20,5) DEFAULT 0,   -- 발주점(이하면 발주)
  ORDER_QTY     NUMBER(20,5) DEFAULT 0,   -- 1회 발주량(lot)
  MOQ           NUMBER(20,5) DEFAULT 0,   -- 최소발주량
  LEAD_TIME     NUMBER DEFAULT 0,         -- 리드타임(일)
  REP_VD_CD     VARCHAR2(18 CHAR),        -- 대표 협력사
  REP_VD_NM     VARCHAR2(200 CHAR)
);
COMMENT ON COLUMN IT_ITEM.REORDER_POINT IS '발주점(현재고+입고예정 이하면 발주제안)';
COMMENT ON COLUMN IT_ITEM.ORDER_QTY IS '1회 발주량(lot)';

-- ---------- MRP 발주제안 ----------
INSERT INTO CM_CODE_GRP (GRP_CD, GRP_NM, REG_ID) VALUES ('MR_STS', 'MRP제안상태', 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('MR_STS', 'SUGGEST', '제안',     1, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('MR_STS', 'ORDERED', '발주생성', 2, 'SYSTEM');
INSERT INTO CM_CODE (GRP_CD, CD, CD_NM_KO, SORT_NO, REG_ID) VALUES ('MR_STS', 'IGNORE',  '무시',     9, 'SYSTEM');

CREATE TABLE MR_SUGGEST (
  ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMP_CD       VARCHAR2(18 CHAR) NOT NULL,
  RUN_YMD       DATE,
  ITEM_CD       VARCHAR2(18 CHAR),
  ITEM_NM       VARCHAR2(300 CHAR),
  UNIT_CD       VARCHAR2(18 CHAR),
  CUR_QTY       NUMBER(20,5) DEFAULT 0,   -- 현재고
  ON_ORDER_QTY  NUMBER(20,5) DEFAULT 0,   -- 입고예정(미입고 발주잔량)
  AVAIL_QTY     NUMBER(20,5) DEFAULT 0,   -- 가용(현재고+입고예정)
  SAFETY_STOCK  NUMBER(20,5) DEFAULT 0,
  REORDER_POINT NUMBER(20,5) DEFAULT 0,
  SHORTAGE_QTY  NUMBER(20,5) DEFAULT 0,   -- 부족
  SUGGEST_QTY   NUMBER(20,5) DEFAULT 0,   -- 제안 발주량
  REP_VD_CD     VARCHAR2(18 CHAR),
  REP_VD_NM     VARCHAR2(200 CHAR),
  STS           VARCHAR2(18 CHAR) DEFAULT 'SUGGEST' NOT NULL,
  SRC_PR_NO     VARCHAR2(30 CHAR),
  DEL_YN        CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  REG_ID        VARCHAR2(18 CHAR),
  REG_DT        TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  MOD_ID        VARCHAR2(18 CHAR),
  MOD_DT        TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE MR_SUGGEST IS 'MRP 발주제안';

-- ---------- 시드: IT-00001 발주정책 ----------
UPDATE IT_ITEM SET SAFETY_STOCK=50, REORDER_POINT=100, ORDER_QTY=200, MOQ=50, LEAD_TIME=7,
       REP_VD_CD='VD-00001', REP_VD_NM=(SELECT VD_NM FROM VD_VENDOR WHERE VD_CD='VD-00001' AND ROWNUM=1)
 WHERE ITEM_CD='IT-00001';

-- ---------- 메뉴 ----------
INSERT INTO CM_MENU (MENU_ID, MENU_NM, UP_MENU_ID, MENU_LVL, URL, ICON, SORT_NO, REG_ID) VALUES ('PRO_MRP', 'MRP/자동발주', 'PRO', 2, '/pro/mrp', 'refresh', 25, 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('ADMIN', 'PRO_MRP', 'MANAGEMENT', 'SYSTEM');
INSERT INTO CM_ROLE_FUNC (ROLE_ID, MENU_ID, AUTH_CD, REG_ID) VALUES ('USER', 'PRO_MRP', 'SAVE', 'SYSTEM');

COMMIT;
